### ISSUE TITLE
Electron-based Apps / System Tray

### ISSUE THREAD

**Issue by ntilotta** [elementary/os#102]
elementary OS Juno 5.0 (Beta 1)

If you open an electron-based app, this usually freezes after minimize/maximize, then for example Atom is transparent if you launch it maximized, and every application loses user' settings after you close and re-open it.

Another thing, I noticed that there is no system tray basically, so how to handle programs and close them effectively without using kill or task manager?

**Comment by cassidyjames** [comment]
Please report separate issues as separate issues. I've filed the first under Gala, the window manager, at https://github.com/elementary/gala/issues/305. The second is that the concept of a "system tray" has been deprecated for years, and the implementation was deprecated for the entirety of the Loki cycle. We've removed it in Juno, and GNOME similarly removed their implementation in their 3.26 release. 

Allan Day wrote [a great post](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/) detailing the history of this area and why it is getting removed in favor of newer, better, more purpose-built APIs. I am also planning on writing up a post specific to elementary OS about the better APIs and patterns that can be used. If cross-platform apps have been written in a way that requires a status icon, and are running on a platform that does not provide status icons, that is a problem with the app and should be reported there. It is not just a problem on elementary OS, but also any vanilla GNOME installation, so the app developers should be responsive if they care about shipping their app on Linux.
