### ISSUE TITLE
Ship Vulkan

### ISSUE THREAD

**Issue by Nine-H** [elementary/os#104]
the package `mesa-vulkan-drivers` is installed by default in upstream ubuntu. `vulkan-utils` provides vulkaninfo a commandline util which would help support this package.

**Comment by codygarver** [comment]
AFAICT this is not installed by default in upstream Ubuntu. I don't see a reason to ship this until then since things that need it should depend on it and drag it in themselves. And since there's nothing using it out of the box, it would just be taking up space. Am I missing something?
