### ISSUE TITLE
Printer won't stay enabled

### ISSUE THREAD

**Issue by seprita** [elementary/os#109]
I have Jono beta1 with all updates installed and HP JetDirect printer added, connected to the router. Printer works but won't stay enabled. If I will enable printer with slider button, it will disable itself after a few seconds.

No such issues with Loki in another computer and with a same printer.

PS. English is not my native language, but hopefully You will understand my description.

**Comment by seprita** [comment]
I did another test and attached the same printer directly to the computer via USB. Issue is same, printer won't stay enabled.

**Comment by danrabbit** [comment]
I believe this was resolved by https://github.com/elementary/switchboard-plug-printers/pull/104
