### ISSUE TITLE
Emoji variants segfault all apps

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#111]
When inserting emoji, right-clicking or click-and-holding an emoji with variants causes the app to segfault. Happens in Slingshot, Code, and Terminal at least.

**Comment by cassidyjames** [comment]
Also happens in Adwaita, so not seemingly a stylesheet issue.

**Comment by cassidyjames** [comment]
@codygarver is backporting that sane at all, or should we talk to Ubuntu desktop folks about backporting it? Otherwise we're stuck with a crashing emoji input stack that takes down entire apps for the next couple years. :grimacing:

**Comment by jmc-88** [comment]
That patch should apply cleanly, provided that you can ship a customized version of `libgtk-3-0` and you don't rely strictly on the Ubuntu base.

**Comment by danrabbit** [comment]
This seems to be resolved now
