### ISSUE TITLE
Plank loses snaps upon update

### ISSUE THREAD

**Issue by PohaoGit** [elementary/os#112]
Apps I kept on dock, their icons missing after apps getting updated. I need to keep them on dock again.

**Comment by jlnr** [comment]
Does this happen with apps installed via AppCenter? So far I've only seen this bug with snaps.

**Comment by PohaoGit** [comment]
I think they are probably installed via snaps.

**Comment by codygarver** [comment]
Plank bugs are tracked on Launchpad, please report your bug here (be sure to mentions snaps): https://bugs.launchpad.net/plank

**Comment by jlnr** [comment]
It seems this bug has been filed on Launchpad already: https://bugs.launchpad.net/plank/+bug/1760433

**Comment by PohaoGit** [comment]
Is Plank still maintained? lastest release is a year ago.
