### ISSUE TITLE
Beta 2 iso doesn't boot past plymouth splash screen

### ISSUE THREAD

**Issue by bigfatbird** [elementary/os#116]
Beta 1 and other linux derivates(Ubuntu 18.04, Ubuntu Mate 16.04) boot just fine.

Beta 2 from 09.20.2018 gets stuck at the elementary logo.

Computer is an Asus R515M

Attached lshw:
[lshw.txt](https://github.com/elementary/os/files/2406379/lshw.txt)

**Comment by bigfatbird** [comment]
Hello, same story for the stable release of elementary OS 5.0 Juno. Just won't boot on that hardware. Let me know if there's anything I can do

**Comment by danrabbit** [comment]
@bigfatbird can you still confirm the issue in Hera?

**Comment by bigfatbird** [comment]
Not right now, as I don't have access to that computer. I will try in a few days if that's enough for you.

**Comment by bigfatbird** [comment]
Works, done. Good job
