### ISSUE TITLE
Digicert root certificate is not included by default

### ISSUE THREAD

**Issue by finetuned89** [elementary/os#117]
In a default installation of elementaryOS (both Loki and Juno), the "DigiCert High Assurance EV Root CA" certificate is missing, which means that Epiphany does not trust web sites that are using SSL certificates signed by that root. An example is a popular website in the Netherlands https://marktplaats.nl. The result is that no resources from that website are loaded:

![marktplaats-no-cert](https://user-images.githubusercontent.com/12174852/45917075-73032280-be70-11e8-8bf3-d6217d9cb093.png)

Installing the Digicert root certificte manually from Digicert solves the problem:

```
wget https://dl.cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt
mv DigiCertSHA2SecureServerCA.crt DigiCertSHA2SecureServerCA.der
openssl x509 -inform DER -outform PEM -in DigiCertSHA2SecureServerCA.der  -out DigicertSHA2SecureServerCA.pem.crt
sudo mkdir -p /usr/share/ca-certificates/extra
sudo cp DigicertSHA2SecureServerCA.pem.crt /usr/share/ca-certificates/extra/
sudo dpkg-reconfigure ca-certificates
```

![marktplaats-with-cert](https://user-images.githubusercontent.com/12174852/45917078-78606d00-be70-11e8-8762-2f0c289e2998.png)

Maybe there is a valid reason for not including this certificate by default, or maybe this certificate can be included by default, since it seems like it's assumed to be included on every machine.

**Comment by finetuned89** [comment]
I would like to contribute a fix, but I am not sure where exactly I would do that. If there is someone who can tell me where I should do a pull request, I'd be grateful.

**Comment by codygarver** [comment]
For security reasons, I don't manually manage what certs elementary OS ships. Instead elementary OS trusts the centralized package `ca-certificates`, inherited from Ubuntu and Debian. 

I think that's where this bug belongs instead, it looks like they're fairly actively managing reports: https://bugs.launchpad.net/ubuntu/+source/ca-certificates
