### ISSUE TITLE
Beta 2 live session only boots with acpi=off

### ISSUE THREAD

**Issue by iamikon** [elementary/os#119]
Hey I have a Razer Blade Stealth where there is an odd issue seeing as no other Ubuntu based system has the issue. Booting into the installer only mode works fine. Booting the live session visually glitches the screen and hard freezes. Booting the live session with acpi=off it boots mostly fine though I am missing a working trackpad. As it hard locks I can't really get any errors from logs or anything. This is a similar issue to what I know some people were experiencing on Loki where upon login the system would do the same thing, visually glitch and hard freeze.

[lshw.txt](https://github.com/elementary/os/files/2412213/lshw.txt)

**Comment by danrabbit** [comment]
OP can this be reproduced in the latest stable ISO from our website?

**Comment by iamikon** [comment]
Was reproduced with the 5.0 release. Waiting for 5.1 to try again. Install
option works but system still locks up as many other Razer products have
noted.

**Comment by danrabbit** [comment]
Thanks for the update! Reopening since it can still be reproduced

**Comment by iamikon** [comment]
This is still an issue with 5.1. I’ve tried all things I can find in regards to this and Razer Blade Stealths and nothing seems to work. Though now acpi=off causes a kernel panic. Elementary is the only 18.04 based system that has any issues. I also believe this is a Pantheon specific issue as the system hard locks as it is loading the desktop and using Pantheon on any other system causes the same hard lock upon attempting to log in.

**Comment by iamikon** [comment]
Also with 5.1 the system can be installed fine. Gets to login fine. Attempt to login static and screen glitch and hard crash no matter what I’ve tried.

**Comment by kgrubb** [comment]
Hey @iamikon, which model of the razer blade stealth are you using? What graphics card does your model have?

**Comment by iamikon** [comment]
I have the 2016 Stealth 12.5” 4K with Intel 7500u and Intel HD 620 integrated graphics. Let me know if I can help in any way.
