### ISSUE TITLE
When returning from suspend, white pixels in Wingpanel corners, graphical errors with workspace background

### ISSUE THREAD

**Issue by yerbestpal** [elementary/os#125]
The white pixels are not always guaranteed to happen, though the graphical errors, which look similar to television static, seem to occur every time. I think this is probably an effect of using an Nvidia driver, which I know historically don't play well with Elementary (or any linux distribution, to be honest) but I thought I'd better mention it regardless. Specifically, I am using Nvidia 410.

**Comment by peteruithoven** [comment]
I'm afraid this is a duplicate: https://github.com/elementary/gala/issues/21
People are working on it: https://github.com/elementary/gala/pull/330
