### ISSUE TITLE
Juno: Slow login after locking screen (black screen) [light-locker ?]

### ISSUE THREAD

**Issue by leonidasv** [elementary/os#126]
I've noticed the login process is very slow after i lock my session or return from suspend mode.

After inputting the password, I have to wait about 10 to 30 seconds for the whole screen to show up again. During this process, the whole display shows a black screen or an outdated "screenshot" from the session.

Mouse cursor works fine, tho, and even change from pointer to a "hand" indicator, for example, while moving, but I can't interact with the content.

Also, I know when I can interact again with my system after some notifications shows up. It looks like the system is awaiting for the notifications to arrive (network connections always shows up if I come from a suspend) but freezes the UI during the process.

Two times I saw the infamous "This session is locked you'll be redirected to the unlock dialog automatically in a few seconds" message, what makes me think it's a bug related to the light-locker package and it's integration with Pantheon. 

![](https://3.bp.blogspot.com/-YM1dZM8XPcE/Udx2yQin1TI/AAAAAAAAPyQ/6d7dEttSczg/s320/light-locker-message.png)

For instance, I'm using Intel HD Graphics and seeing this behaviour since Juno Beta 2.

**Comment by amarzano** [comment]
Hi,

Same issue for me, using Dell laptop and nouveau driver.

**Comment by o-alquimista** [comment]
I think this should be reopened. I have the same symptoms with an AMD RX 560 graphics device. Black screen with a delay after typing the login password and pressing Enter.

**Comment by natanielmendes** [comment]
I also this this should be reopened, same problem with NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] here. Black screen with a delay after typing the login password and pressing Enter.

elementary OS 5.1 Hera - GTK 3.22.30

**Comment by mpalu** [comment]
Same here. Freezes after unlock, with no black screen.

NVIDIA Geforce 940MX - nvidia-driver-435
elementary OS 5.1 Hera - GTK 3.22

**Comment by tdias25** [comment]
same here, freezes with black screen for a couple of seconds

NVIDIA GeForce MX130

**Comment by mpalu** [comment]
@lewisgoddard is it possible to reopen this issue?
