### ISSUE TITLE
Juno: Graphical issues after wake up from suspension (iMac 2007)

### ISSUE THREAD

**Issue by mauritslamers** [elementary/os#133]
After waking up from suspension my iMac 2007 has severe graphical issues rendering the machine useless until after a full restart.

![20181021_193436](https://user-images.githubusercontent.com/14616/47270245-445c9280-d569-11e8-82e1-c209b938bf76.jpg)

The same distortion of the image persists in non X environments, such as when switching to a different terminal through ctrl-alt-F1.

**Comment by peteruithoven** [comment]
What happens in other distro's?

Seeing that absolutely everything is "distorted" this seems like something else than: https://github.com/elementary/greeter/issues/131

**Comment by davidmhewitt** [comment]
Going to close this due to age. It looks like it was likely a driver issue which we can't do anything about anyway.
