### ISSUE TITLE
No sound after reboot

### ISSUE THREAD

**Issue by Djaler** [elementary/os#136]
If I reboot or relogin with connected audio device (no matter, headphones or speakers), then I have no sound after system login. I need to disconnect audio cable and connect it again. Then all works good

**Comment by davidmhewitt** [comment]
This sounds like a driver issue as I've never experienced this on any hardware.

If you are still experiencing this, please open an issue on the Ubuntu linux kernel bugtracker, as elementary ships an unmodified Ubuntu kernel with exactly the same driver stack.
