### ISSUE TITLE
Elementary 5.0 Juno, Error: couldn't get uefi db list

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#141]
_From @tomas-nielsen on October 25, 2018 8:24_

When I try to install elementary 5.0 juno from a usb I instantly get

`couldn't get uefi db list`

And it just stops getting any further. The same happens when I try to start elementary live from the usb.

I have searched the web, and some says it's related to secure boot being enabled, but I have checked and it's disabled, also I tried changed the boot option from uefi+legacy to just uefi, but that didn't do the trick either. I have also updated my BIOS to the latest update.

I'm all out of ideas. Could it be a problem with the kernel?

_Copied from original issue: elementary/installer#361_

**Comment by danrabbit** [comment]
Issues like this should be resolved by the new Hera build system
