### ISSUE TITLE
/boot/efi not installed properly to external media

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#142]
_From @eljefuri on October 27, 2018 4:21_

When Elementary is installed to e.g. a microsd card and a format-and-install situation, the installer does not correctly setup the /boot/efi folder on the card. It instead uses the local hd/ssd as the EFI partition and includes that in /etc/fstab. The first partition of the microsd card, which should be the SD card, is partition and formatted, but empty.

_Copied from original issue: elementary/installer#362_

**Comment by eljefuri** [comment]
Is this not a high-priority issue? To be clear, it renders the install unbootable on another UEFI machine.

**Comment by codygarver** [comment]
Anybody know if this happens with normal Ubuntu?

**Comment by danrabbit** [comment]
@eljefuri can you confirm if this was resolved in Hera?

**Comment by davidmhewitt** [comment]
We never got a response to follow up questions and this sounds like a Ubiquity issue anyway. elementary OS 6.0 won't be using Ubiquity so it can be re-verified and re-reported if necessary.
