### ISSUE TITLE
installer keeps crashing on grub install

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#143]
_From @THN1 on October 24, 2018 16:33_

Hi team
the eOS 5.0 installer keeps crashing reproducibly (3 trials) on the grub install /dev/sda (or sdaN) step on my multiboot system (N=8). The resulting partial install is unbootable and unusable.
THN1

_Copied from original issue: elementary/installer#359_

**Comment by danrabbit** [comment]
Closing because we're moving to the new installer
