### ISSUE TITLE
WiFi worked on installer USB but not after installation

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#144]
_From @Coi-l on October 24, 2018 16:52_

Yesterday I installed Juno but I ran into a problem with the WiFi.

Booting from the live disk and following the installer steps the installer could scan and connect fine to my wifi at home.

However after installation WiFi was not working. There was no interface for the wifi even.

After doing some digging I found that this command and a reboot helped me:
sudo apt install firmware-b43-installer

The computer is an old macbook pro (5.1) with a Broadcom bcm4322 chipset (14e4:432b).

I am 100% sure that the live disk and the installed system was using different drivers for the chipset. The b43 driver was not loaded on the live disk.

Fortunately it was such an old macbook it had an ethernet port so I could just plug it in and do the apt install :)

_Copied from original issue: elementary/installer#360_

**Comment by cassidyjames** [comment]
This repo is for the new installer which is not being used in Juno yet.

**Comment by ArtemPopof** [comment]
I have similar problem with my Broadcom 4360 (14e4:43a0). Wifi is broken after Juno installation. I had to manually setup broadcom-wl driver to be able to use wifi, after installation bcma driver was on. Actually, I had this problem with Ubuntu 18.04 and Fedora 29 also, so it's may be related to kernel somehow. Ubuntu 18.10 don't have this issue.

**Comment by danrabbit** [comment]
I believe this is fixed in Hera
