### ISSUE TITLE
Juno 5 - Settings > Display selections don't always apply with an external monitor

### ISSUE THREAD

**Issue by umarov** [elementary/os#147]
Computer: Dell XPS 13 9360
OS: elementary OS 5.0 Juno
kernel: Linux 4.15.0-38-generic
GTK: GTK+ 3.22.30
System Settings: 2.3.4

- Rearranging monitor placement :heavy_check_mark: (Works)
- Selecting primary monitor :question: (doesn't always stick)
- Disabling built-in screen :x: 

It always prompts me to "Keep the settings" or revert back to previous. Sometimes I have to click on "Detect Displays" to have the actual settings to reflect in the Display settings UI.

Right now my work around is using Super + P to cycle between different monitor modes. One of the modes is the laptop display as off and external monitor on. I know I can also do it from the terminal with `xrandr`.

**Comment by peteruithoven** [comment]
@umarov thanks for reporting. It would however be much better to keep one issue limited to one issue. 
I think these issues are mainly about the Display settings, which is kept in this repo:
https://github.com/elementary/switchboard-plug-display
(The Report problem button in the About settings can help you find the right repo)

In regards to disabling built-in screen there is an existing issue: https://github.com/elementary/switchboard-plug-display/issues/131

You could open a new issue on primary monitor selection.
