### ISSUE TITLE
Kernel panic booting live usb on Dell XPS 13

### ISSUE THREAD

**Issue by Richard-Payne** [elementary/os#149]
Kernel panic booting live usb on Dell XPS 13, with Ubuntu on the hdd.
ISO: elementaryos-5.0-stable.20181016.iso
Boot mode: EFI, not secure

I was going to attach a screenshot but github is just reporting "Something went really wrong and we can't process that file".

The important parts that I can spot are:

```
ACPI Error: [_SB_.PCI0.RP05.PXSX] Namespace lookup failure, AE_NOT_FOUND (20170831/dswload2-191)
{ repeat for 20170831/psparse-550 and 20170831/psarg-364 }

Initramfs unpacking failed: broken padding
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(1,0)
CPU: 6 PID: 1 Comm: swapper/0 Not tainted 4.15.0.-36-generic #39-Ubuntu
Hardware name: Dell inc. XPS 13 9370/0F6P3V, BIOS 1.0.2 12/06/2017

{ stack trace }
```
The installed Ubuntu system has no issues booting or running.

**Comment by vjr** [comment]
Please check your downloaded ISO hash matches this SHA256 hash -> a8c7b8c54aeb0889bb3245356ffcd95b77e9835ffb5ac56376a3b627c3e1950f

Just to eliminate the possibility of a bad ISO file download or bad USB stick written?

**Comment by vjr** [comment]
What software did you use to write the live usb? Try another attempt or different tool?

**Comment by Richard-Payne** [comment]
> Please check your downloaded ISO hash matches this SHA256 hash -> a8c7b8c54aeb0889bb3245356ffcd95b77e9835ffb5ac56376a3b627c3e1950f
> Just to eliminate the possibility of a bad ISO file download or bad USB stick written?

Yes, the hash checks out.

> What software did you use to write the live usb? Try another attempt or different tool?

I've tried both the Linux Mint USB Image Writer and the Ubuntu Startup disk creator.  Both tools created a bootable Mint USB and both produced an Elementary USB which failed to boot.

**Comment by Richard-Payne** [comment]
Hmm, maybe it is a problem with the image write.  I just tried to boot my desktop pc from it and got the same error.

**Comment by vjr** [comment]
The elementary.io installation guide page suggests you try the Unetbootin tool on linux.

**Comment by Richard-Payne** [comment]
Have just done it use dd and it now boots.  It did still display the ACPI errors I listed (not sure if they're normal, but it no longer panics.

**Comment by lewisgoddard** [comment]
I think Unetbootin does something special (with EFI maybe?). The ACPI error is probably just the Kernel or OS trying to figure out what hardware you have for installation/boot in a new environment.
