### ISSUE TITLE
Password issue with OEM install

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#152]
Reported by Microtech team:

>If you make MANUFACTURER INSTALLATION and someone later setup own account then password prompt after close the lid or sleep the system not appear at all , just is going straight to system  - I checked in settings if those settings are on .. and they are on but still password not appears . 
I also tried add another account but then still password not working ( not appear after close lid or sleep system ) 

>If you make normal installation elementray os then problem not exist - only on manufacturer installation.

I am still trying to confirm this and can provide more details once I have.

**Comment by cassidyjames** [comment]
It looks like the issue is reproducible as follows:
1. Perform an OEM install (see: https://help.ubuntu.com/community/Ubuntu_OEM_Installer_Overview)
2. Reboot, and set up a user as if you are the end user.
3. Once logged in, suspend your device

Expected:

The device suspends, then upon waking is locked (matching the default settings)

Actual result:

The device resumes and does not lock.

Also note that locking, both from the keyboard shortcut and the indicator, do nothing.

**Comment by danrabbit** [comment]
Gonna close this since there's no such thing as a separate OEM install anymore
