### ISSUE TITLE
Display scale configurations

### ISSUE THREAD

**Issue by DevWaweru** [elementary/os#153]
The display is unusually zoomed in. My screen resolution is at 2560 x 1440 but icons are larger than normal, unlike in loki where the maximum resolution I could keep up with was 1920 x 1080 which kept things neat

**Comment by IvanAditazz** [comment]
hi @cassidyjames I'm facing the same issue, I connect an external monitor LG - 1920 x 1080 (full hd) and everything is zoomed twice, I try to fix it using"

`xrandr --output HDMI-1 --scale 2x2`

if fix it but the screens made something really weird flickering when I move windows and adding some chess pattern (white and black squares)

if I use 
`gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <1>}]"`

My main screen goes really small (like 50% zoomed out) and the external looks fine.

I made some research but all  I finds indicates that Juno is not handling well the scaling for external monitors.

There is any solution? thanks

**Comment by danrabbit** [comment]
Display resolution can be changed in System Settings → Displays.

It is not currently possible to have different scales per display (mixed DPI).
