### ISSUE TITLE
wifi cut

### ISSUE THREAD

**Issue by RafoxSama** [elementary/os#155]
Hello I have a break of wifi and when I open the menu I see that!
![capture d ecran de 2018-11-24 11-19-29](https://user-images.githubusercontent.com/12686030/48967022-0e348780-efdb-11e8-92ee-2b9affa6aa41.png)

**Comment by peteruithoven** [comment]
You're going to have to explain yourself a bit better.

**Comment by RafoxSama** [comment]
> You're going to have to explain yourself a bit better.

OK how ? any specific questions to help me ?

**Comment by peteruithoven** [comment]
What do you mean with wifi cut / break? Is it disconnected? You don't receive data? 
How do you see this in the menu or the screenshot you've added? 
Please read: https://elementary.io/docs/code/reference#reporting-bugs

**Comment by danrabbit** [comment]
Closing as "incomplete" since OP never responded
