### ISSUE TITLE
Boot splash image is stretched (incorrect Window dimensions in script)

### ISSUE THREAD

**Issue by neogeographica** [elementary/os#166]
It took me a while to realize that the elementary "e" logo is supposed to be circular... on my Juno system the boot splash image is an oval, noticeably wider than it is tall.

I added a debug line to the theme script and determined that when it invokes Window.GetWidth() and Window.GetHeight(), it gets 1600 and 1200. However my monitor's resolution (the only one it supports, and the one shown in elementary's display settings) is actually 2560x1440.

Edit: Hmm the aspect ratio mismatch doesn't completely explain the image's appearance, as I only had to scale its width by 0.9 to make it appear circular. I did that when I was originally guessing that the script was assuming a 16x10 aspect... but 1600x1200 is not that.

FWIW I see at least one report of this happening pre-Juno, at https://elementaryos.stackexchange.com/questions/5554/plymouth-boot-splash-stretched-with-widescreen-monitor ... also someone using a 16x9 aspect ratio monitor.

**Comment by neogeographica** [comment]
Going down the rabbit hole further on this one... it looks like it may just be a consequence of my card's VESA modes, how it chooses to show/stretch those on this monitor, and possibly the fact that I'm using the proprietary drivers.

So in my case maybe the answer is to edit grub settings (or just mess with the image proportions in the theme script).

I don't know if there's anything you guys can do to make it less likely for your boot logo to get mutilated, so I'll leave it up to you whether to close this issue.

**Comment by peteruithoven** [comment]
Are you referring to the logo on the black background?

I customized my grub based on the grub theme in: https://github.com/pop-os/grub-theme/tree/master/usr/share/grub/themes/pop
Probably using the logo from: https://www.gnome-look.org/p/1180195/
But I don't think that impacts the logo on black part, which is probably the splash part?
I noticed that Pop OS repo also has a script to disable splash, maybe you could try that?
https://github.com/pop-os/grub-theme/blob/master/etc/default/grub.d/grub-pop-disable-splash.cfg

**Comment by neogeographica** [comment]
It's the stylized "e" on the black background shown at boot time. This is drawn by the Plymouth theme "elementary". That theme has a script that queries the size of a Window object and uses that info to scale and place the logo image.

In this case, the Window object is claiming to be 1600x1200 although my monitor is 2560x1440. 1600x1200 is the highest/best VESA mode supported by my graphics card, so I guess that's what is behind this. And apparently when that resolution is used on this monitor (at least in this process during boot) the images shown will get stretched.

I might be able to mess around with grub settings to force a different resolution to see if those have better results. But since I don't have any "better" VESA modes or any that are 16x9, that doesn't sound promising. It's a lot easier just to edit the theme script to have it scale the image to compensatorily un-squash it, so that's what I've done.

Ideally the script would be able to figure this out on its own with some sorts of queries, but I don't have enough Plymouth/grub/VESA/whatever smarts to know if that is even possible.

**Comment by davidmhewitt** [comment]
I'm going to close this as we've recently reworked all of the bootsplash process for elementary OS 6.0. If you're still experiencing this in the daily builds of elementary OS 6.0, or once elementary OS 6.0 releases. Please open a new issue at https://github.com/elementary/plymouth-theme
