### ISSUE TITLE
Update packagekit to 1.1.12

### ISSUE THREAD

**Issue by tintou** [elementary/os#168]
The aptcc backend had lot of improvements, it'd be nice to consider an upgrade

**Comment by cassidyjames** [comment]
@codygarver it looks like 1.1.12 is in Disco: https://launchpad.net/ubuntu/+source/packagekit

**Comment by davidmhewitt** [comment]
This is now in the `elementary/staging` PPA for testing. Merging https://github.com/elementary/os-patches/pull/71 and a few button clicks in Launchpad will push this to `os-patches` once we're happy with it.

**Comment by cassidyjames** [comment]
Available in stable! https://code.launchpad.net/~elementary-os/+archive/ubuntu/os-patches/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic
