### ISSUE TITLE
Could not use UEFI Full disk encryption

### ISSUE THREAD

**Issue by DonPavlov** [elementary/os#172]
If I started the iso image in UEFi Mode, I was unable to partition the hard drive in full disk encryption mode. I selected the auto partitioning and it failed. During the installation not gracefully.

The issue was gone if I start it in legacy mbr mode.
The problem then is, that I could not add the old windows partition via os prober to the grub menu. Because windows 10 is using efi and eos was not.

**Comment by aral** [comment]
Hey @cassidyjames, is full disk encryption an option in the current 5.1.7 Hera installer? On the StarLabs LabTop Mk IV, when I initially ran the installer yesterday, it wasn’t. Just ran it again from the USB key and the first setting I get is the language choice, nothing about full disk encryption. I must be missing something basic but I’m not sure what.

**Comment by DonPavlov** [comment]
Not relevant for me anymore, would need retesting by a third party.
