### ISSUE TITLE
Logout after taking action in system

### ISSUE THREAD

**Issue by Frzoen** [elementary/os#182]
I have an issue with system. Trying to change monitor layout in system causes logout. Same with trying to open we browswer. 
System specs:
``` 
Intel i5 2500k
Nvidia GTX1060
8GB RAM
AOC 24B1XH x3
```
fresh install of Elementary OS with 3rd party drivers choosed during install using
elementaryos-5.0-stable.20181016 iso

After login there is blank screen, it can be resolved with removing .Xauthority and restart of lightdm but no changes are made or programs running. It's possible to switch to another window with ie. ctrl+alt+1 where terminal is running.

Video with problem:
https://photos.app.goo.gl/rCzqxWzMnrpDj2Je7

**Comment by davidmhewitt** [comment]
Closing as we never got a response from OP. Sounds like an issue with graphics drivers though.
