### ISSUE TITLE
Enable touch in Mozilla projects by default

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#185]
It turns out there's an environment variable Firefox and other Mozilla projects look for by default for touch input. I.e. you can add `MOZ_USE_XINPUT2=1` to `~/.pam_environment` and upon a reboot, Firefox works with touch scrolling, pinch-zoom, etc. [This works out of the box in Fedora](https://twitter.com/killyourfm/status/1102867905493065729), so it's possible they're setting this by default there.

**Comment by decathorpe** [comment]
In fedora, firefox is executed via a wrapper script, which sets this environment variable (among others).

https://src.fedoraproject.org/rpms/firefox/blob/master/f/firefox.sh.in

**Comment by tintou** [comment]
Fedora is also using Wayland and I believe that they are now using the Wayland backend in Firefox instead of XWayland so this requires a bunch of tests before even considering it as viable on Ubuntu-based distro

**Comment by decathorpe** [comment]
> Fedora is also using Wayland and I believe that they are now using the Wayland backend in Firefox instead of XWayland so this requires a bunch of tests before even considering it as viable on Ubuntu-based distro

@tintou Well, that doesn't affect Pantheon at all. Unless it magically grew wayland session support without me noticing :wink:

**Comment by cassidyjames** [comment]
@tintou I've been using this on elementary OS for quite some time now and it works exactly as expected. I understand we'd need to test more, but if Fedora is shipping this environment variable regardless of backend and session, and ships Firefox by default, I think it's well-tested enough to ship for us.

**Comment by danrabbit** [comment]
Closing since we don't ship Firefox. This should be filed in Launchpad probably
