### ISSUE TITLE
Voice Assistant integration

### ISSUE THREAD

**Issue by MrGrymReaper** [elementary/os#187]
At the moment there's no voice assistant integrated into elementary, since voice is the future for interfacing with and operating the computer it would be worth at least researching integrating one into elementary. Though it would be better if it was integrated into elementary in a fashion which respects privacy especially if the assistant itself respected user privacy and agency.

Since the big tech voice assistants can typically not respect a user's privacy may I suggest one like Mycroft AI ([https://mycroft.ai](https://mycroft.ai)). There's likely others though I currently can't think of any off the top of my head, so feel free to add them in a comment to this issue.

**Comment by cassidyjames** [comment]
While I'm not sure we'd implement Mycroft ourselves, an app developer is welcome to submit a Mycroft (or other voice assistant) app to AppCenter via [developer.elementary.io](https://developer.elementary.io).

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/triage/issues/97.
