### ISSUE TITLE
Make hibernation work

### ISSUE THREAD

**Issue by rubydesign** [elementary/os#189]
There is some talk of removing the hibernation option over in https://github.com/elementary/switchboard-plug-power/issues/78
While this makes sense, as hibernation does not work, i would really suggest to get hibernation to work.
Coming from mac it is a little strange to see the state of this (and power/performance management) in Linux and i think it would really help users. Hibernation is not something that a normal user should have to deal with, and it would make Elementary stand out if it actually worked.

My machine (and any i tried), use 10-20% battery per hour when not plugged in, when not used. Very little difference between just being on, display sleeping, suspend or anything i know to try. My hope is that hibernation would fix.

I would offer to help (or i do) but am a newbie and know nothing much more than that my battery is draining :-)

**Comment by RicardoEPRodrigues** [comment]
Hello @rubydesign, can you reopen this issue? I feel it is a relevant issue and should be opened. Thank you.

**Comment by rubydesign** [comment]
There was no feedback. So i think you opinion is not shared by the powers that be (people with commit right).
But if they do feel it is important, they can reopen it.
I do not use Elementary and do not want to be the author of a dead issue that even i do not care about.

**Comment by RicardoEPRodrigues** [comment]
You're right. In two years they could have said anything, there ~~is~~ was plenty of time.
