### ISSUE TITLE
Apply a patch do plank for changing badge color

### ISSUE THREAD

**Issue by donadigo** [elementary/os#190]
Adding this patch to plank: https://gist.github.com/donadigo/787e9fa3689bcaf8a91eed3a71bad228 will unlock https://github.com/elementary/stylesheet/pull/376 which in turn will also unlock https://github.com/elementary/switchboard-plug-pantheon-shell/pull/134 to be merged.

The patch adds a new setting to change the badge color independently of the theme accent color.

**Comment by danrabbit** [comment]
It looks like this was merged into Plank master https://git.launchpad.net/plank/commit/?id=96bbb1d2a02e326247aa1ff6adb01f8e18da50af
