### ISSUE TITLE
Backport the newest FontConfig to juno

### ISSUE THREAD

**Issue by lainsce** [elementary/os#191]
The package currently in juno/bionic repos lacks a bug fix for the `fc-cache` command crashing Firefox, and Webkit related browsers.

Suggested to backport the latest packages to Juno, so that this is fixed.

**Comment by danrabbit** [comment]
@lainsce is there an Ubuntu issue report for this in Launchpad? If not, can you file one?

**Comment by lainsce** [comment]
@danrabbit I have found this bug filed here, so I'm not gonna duplicate-issue it :slightly_smiling_face: 
https://bugs.launchpad.net/ubuntu/+source/fontconfig/+bug/1832787

**Comment by danrabbit** [comment]
I'm going to close this as "Out of Scope" since there is already a confirm and high priority issue open against the upstream Ubuntu release
