### ISSUE TITLE
disk naming/renaming for encryption / greeter

### ISSUE THREAD

**Issue by bumbleblue** [elementary/os#193]
(Hope this is the right place for it!)

## Description 
Just installed my brand new elementaryOS and opted for full-disk encryption. When I start up, I have to enter my encryption key underneath a box with the name of my hard drive, `disk sda3_crypt`.
However, A) I don't know if that's the name of my drive, and B) the aesthetics of that could be better.

## Suggestion
Instead of displaying the name of the hard drive, make the copy "enter decryption key" or "decrypt hard drive" or "unlock your drive" or ... instead of displaying the string of actual hard drive name.
If name of drive is important for whatever reason, I suggest giving people the option to name the hard drive either during or after the installation. 

That way no one has to read `disk sda3_crypt` every time they start up!

**Comment by davidmhewitt** [comment]
We have a similar issue with more detail here: https://github.com/elementary/plymouth-theme/issues/13

I'll close this issue in favor of that one.
