### ISSUE TITLE
casper/initrd missing 

### ISSUE THREAD

**Issue by danrabbit** [elementary/os#196]
Latest daily doesn't boot on metal. Looks like we either need to rename initrd.lz or symlink so that it will boot.

**Comment by fabianthoma** [comment]
I can confirm that pointing Grub at the file /casper/initrd.lz instead of /casper/initrd in the file /boot/grub/grub.cfg solves this issue and makes the iso bootable with EFI Systems

**Comment by danrabbit** [comment]
Closing as a duplicate of 200
