### ISSUE TITLE
Screen goes gibberish after waking up

### ISSUE THREAD

**Issue by AmitJoki** [elementary/os#207]
I've had various instances of this occuring. Basically whenever the screen sleeps, either due to inactivity or due to lock screen, whenever it wakes up after sometime, I get the following gibberish:

![Screenshot from 2019-06-28 13-30-37](https://user-images.githubusercontent.com/5158554/60327661-165a0880-99aa-11e9-9ab3-61fc1f6e5138.png)

The gibberish part is all over most of the times and returns to normal after I press super key or interact with it. I am on Elementary Juno.

**Comment by peteruithoven** [comment]
This looks like a graphics card (driver) issue. If I had to guess I'd say you have a Nvidia and use the proprietary driver?
In what kind of places do you see this gibberish / these glitches? 
In for example Gala, the elementary OS window manager we had to force refreshes to fix these kind of issues in the wallpaper and the rounded corners of the screen. 
I doubt we can do anything for electron based apps.

**Comment by AmitJoki** [comment]
Yes, I have Nvidia driver and have installed the corresponding driver from the App Center. It is not limited to Electron apps. The greeter when waking up after a lock time is fully black except for the password area.

**Comment by peteruithoven** [comment]
Thanks for the information. except for when this happens inside elementary OS made things I'm afraid there is little we can do. 
(We're working on a new Greeter so that's hopefully already fixed)

**Comment by tdias25** [comment]
this also happens to me, also nvidia driver
