### ISSUE TITLE
Replace Cerbere with systemd --user to launch session

### ISSUE THREAD

**Issue by peteruithoven** [elementary/os#208]
Why use Cerbere instead of Systemd to keep Plank and Wingpanel working?

Answer from Cassidy: 
> I think because Cerbere predated systemd, honestly. There's another reason but I forget.
> I think there's something about it being a user process instead of a system process maybe?
> Last time it was brought up, Cody said:
>>  so just to sum up the situation since it keeps coming up and we can all copy pasta this to each other next time, we all agree:
>>   - cerbere is not an elegant solution
>>   - cerbere has a noble purpose, to respawn crashes that would break the session
>>   - cerbere has no comparable replacement upstream or elsewhere yet  
>
> https://wiki.gnome.org/Initiatives/SystemdUser

David Hewitt:
> I had a look and it's difficult to have just the panel and plank launched with systemd without having the whole session launched with systemd
> And that's a whole other can of worms because of gnome-session
> It's something that I/we would like to replace
> But it's not that high on the priority list since what we have works

**Comment by benwaffle** [comment]
https://guadec.ubicast.tv/videos/managing-gnome-sessions-with-systemd_85843/

**Comment by davidmhewitt** [comment]
We already replaced Cerbere. Not with systemd yet, but there's a more specific issue about this somewhere else.

**Comment by aral** [comment]
@davidmhewitt Hey David, what was it replaced with? I’m trying to kill Wingpanel so I can take a scripted screenshot without it in it and it’s not been easy.

**Comment by davidmhewitt** [comment]
It was replaced by `gnome-session` autostarts. If you kill it twice within 60 seconds, I believe it should stop restarting

**Comment by aral** [comment]
@davidmhewitt Thanks so much :)
