### ISSUE TITLE
Setup issue templates

### ISSUE THREAD

**Issue by peteruithoven** [elementary/os#209]
I think we should setup issue templates in elementary OS (more consistently). I'm hoping we'll have to less frequently have to ask people to include screenshots / screen recordings and to elaborate past a one sentence report. People forgetting to include that they're on Arch, have certain customizations etc. Hopefully it will improve the quality of reports in general. 

Only the following repo's have issue templates and some of these ask irrelevant information, like smartphone details.
- Installer: https://github.com/elementary/installer/issues/new/choose
- Website: https://github.com/elementary/website/issues/new
- Camera: https://github.com/elementary/camera/issues/new
- Switchboard: https://github.com/elementary/switchboard/issues/new

Search:
- https://github.com/search?q=org%3Aelementary+filename%3Abug_report.md&type=Code
- https://github.com/search?q=org%3Aelementary+filename%3Aissue_template.md&type=Code

Ideally we cater the template to the specific projects, but we have to start somewhere.

How: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

Example of templates in action: https://github.com/peteruithoven/resizer/issues/new/choose

Good examples:
- Signal: https://github.com/signalapp/Signal-Desktop/issues/new
- ...

I'm looking for more good examples, please share.

**Comment by kgrubb** [comment]
I played around with the signal issue template + the atom issue template. Here's a bug report example for greeter. Let me know what you think!

Example:
```
<!--
By filing an Issue, you are expected to comply with the elementary code of conduct: https://github.com/elementary/greeter/blob/master/CODE_OF_CONDUCT.md
-->

### Prerequisites

* [ ] I have searched open and closed issues for duplicates.
<!--
https://github.com/elementary/greeter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
-->

* [ ] I have followed all of the applicable steps in the OS Development guide.
<!--
https://elementary.io/docs/code/os-dev
-->

* [ ] I have reproduced the issue on the master branch.
<!--
Sometimes a fix is in the works, but isn't pushed out to the public yet. Make sure to follow the project's readme to install the latest changes.
-->

### Description

<!-- Description of the issue -->

### Steps to Reproduce

1. <!-- First Step -->
2. <!-- Second Step -->
3. <!-- and so on… -->

**Expected behavior:**

<!-- What you expect to happen -->

**Actual behavior:**

<!-- What actually happens -->

**Reproduces how often:**

<!-- What percentage of the time does it reproduce? -->

### Platform Information

<!--
Take a screenshot of your computer's platform information using your `PrtSc` or `Print` button! Your computer's platform information can be found by opening the application drawer, selecting "System Settings", then selecting "About".
-->

### Additional Information

<!-- Any additional information, configuration or data that might be necessary to reproduce the issue. -->
```

And here's how it renders:

### Prerequisites

* [ ] I have searched open and closed issues for duplicates.

* [ ] I have followed all of the applicable steps in the OS Development guide.

* [ ] I have reproduced the issue on the master branch.

### Description

### Steps to Reproduce

1.
2.
3.

**Expected behavior:**

**Actual behavior:**


**Reproduces how often:**

### Platform Information


### Additional Information

**Comment by peteruithoven** [comment]
Some notes.
- I personally don't think we can expect everyone to try out the master branch.
- I'd like to limit any repo specific texts / links since we have to add this to a lot of repo's

I've opened a first PR, let's move the discussions there: 
https://github.com/elementary/gala/pull/581

**Comment by danrabbit** [comment]
This has been done! :)
