### ISSUE TITLE
button minimize doesn't appearance in all windows

### ISSUE THREAD

**Issue by Luigidefra** [elementary/os#212]
i set "close,minimize:maximize" in dconf app to the section button-layout but minimize button appeacance only in some windows (eg in PhpStorm it appearance, in Chrome it doesn't appearance )

**Comment by peteruithoven** [comment]
I don't think this is an option elementary OS supports. 

Also in Chrome/Chromium unless you're enabled "Use system title bar and borders" the headerbar is drawn by Chrome/Chromium itself so there is little we can do. This is called "client side window decorations".
