### ISSUE TITLE
Move files using the title bar

### ISSUE THREAD

**Issue by BenoitDuffez** [elementary/os#213]
My request is about Evince. I would have submitted it there, but I feel this is more related to its integration into Elementary OS. I'm not sure though, so please bear with me and indicate me if this is not the right place.

I love Elementary on my work laptop, and I use a mac at home. What I love from both is the ability to quickly open PDF files with a fast viewer. What I love on the mac and I feel is missing on Elementary, is the ability to rename/move the file from the title bar of the PDF viewer.

Here's how it looks like on a mac (screenshot taken randomly from Google Images):

![rename and move files from the title bar](http://cdn.osxdaily.com/wp-content/uploads/2014/03/move-a-file-while-open-from-titlebar.jpg)

Basically the title bar contains the file name, (right) clicking it opens a popup allowing to rename the file, and a quick file browser to move the file to recent folders, and a button to open a full folder browser to place it in a non-recent folder.

This is very useful and helps productivity, e.g. when someone sends you a document opened from another app (likely in /tmp/mozilla/whatever) and you want to save it to $HOME/Documents/Products/etc

**Comment by BenoitDuffez** [comment]
Thanks for the hints about issue classification. I'll see what I can do on the gnome project, though I doubt they have control over the title bar behavior (which seems to me more like an OS feature or at least an OS-driven UI component). But hey, the note app you mention did that so why not Evince.

**Comment by cassidyjames** [comment]
@BenoitDuffez in modern GNOME apps, the decoration/titlebar is client-side, meaning it's drawn by the app itself. So this would need to be implemented in each app.

**Comment by BenoitDuffez** [comment]
OK cool, thanks for the clarification.
