### ISSUE TITLE
Hotkeys do not work when switching to Russian

### ISSUE THREAD

**Issue by Dez1gner** [elementary/os#215]
Many programs stop replying to the letter keys on the keyboard when switching to the Russian layout. For example, a blender. Both Inkscape and Gimp have problems. In Ubuntu, POP! OS, Manjaro, Open Suse, no problem.
i.e. CTRL+C or the letter keys (normal typing)

**Comment by peteruithoven** [comment]
I've found some old, not migrated relevant seeming issue reports:
- https://bugs.launchpad.net/gala/+bug/1641463
- https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/1226962

**Comment by Dez1gner** [comment]
Thank you so much for paying attention.
I really, really love EOS, but I can't use it because of this problem.

**Comment by h2ash** [comment]
Hotkeys don't work too in VS Code with Russian/Ukrainian keyboard.

**Comment by santileortiz** [comment]
Specifically for the case you mention in Blender, can you try disabling the shortcut to switch input methods in System Settings > Layout. By default it's set to Alt+Shift which is probably conflicting with the keybinding you are trying to use in Blender.

We've heard from a few people in Russia that the Alt+Shift keybinding is the expected default for this functionality. Have you ever used layout switching?.

**Comment by Dez1gner** [comment]
I have language switching set to CapsLock.
This is exactly the Elenentary problem. It's not a keyboard shortcut conflict issue. This is not a problem with Blender settings.
This problem also concerns the speed of switching languages, it is so low that it becomes impossible to use Elementary in two languages. The switchover may take several seconds.
This is the reason that has prevented me, a professional 3D artist, from using Elementary for 5 years.

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/gala/pull/1589.
