### ISSUE TITLE
[juno] Suspend does not fully sleep

### ISSUE THREAD

**Issue by ainiml** [elementary/os#217]
Putting the system in suspend mode, the laptop is still on.

I noticed this when the computer was very warm taking out of my laptop, and the battery had drained more than it would

**Comment by peteruithoven** [comment]
Could you include some hardware info? Maybe as a screenshot of the System Settings > About page? 

If I had to guess you have a Nvidia graphics driver and you're using the proprietary driver? This can create these kinds of issues. Not really anything we can do about.

**Comment by ainiml** [comment]
@peteruithoven Dell XPS 13 2019

So it'll be an integrated Intel video

Sleep mode works perfectly fine without ElementaryOS, however

This occurs on a Dell XPS 13 2016 model as well

**Comment by jlnr** [comment]
> Sleep mode works perfectly fine without ElementaryOS, however

On Windows, or Ubuntu, or...?

**Comment by dbhowell** [comment]
I'm pretty sure this is a kernel issue, see:

https://bugzilla.kernel.org/show_bug.cgi?id=199689
and
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1808957

I upgraded to kernel 4.19 which seems to solve the problem.

**Comment by ainiml** [comment]
@jlnr Ubuntu 18.04 base.

**Comment by peteruithoven** [comment]
As far as I know elementary OS uses the same kernel as Ubuntu 18.04, because elementary OS is build on the Ubuntu LTS.

**Comment by ainiml** [comment]
@dbhowell you're right it is the kernel

It didn't happen on the XPS13 MLK (9360) model, however. 

I'll try out the new kernel

**Comment by ainiml** [comment]
Updated to `5.2.2-050202`, so we'll see how things go

**Comment by ainiml** [comment]
The frequency that Elementary checks for updates locks up apt, and breaks my install scripts, https://github.com/TheShellLand/antsable/blob/master/playbooks/ubuntu-readyup-18.x.yml

So I've had to stop using Elementary. Closing ticket.
