### ISSUE TITLE
Upon switching with nvidia-prime, no top bar & no plank

### ISSUE THREAD

**Issue by JeffLabonte** [elementary/os#219]
Hello guys! 

By the way, love the distro! You guys are doing a great job! 

I solved an issue with the `nvidia-prime` package that I had using one my script, and it requires to restart the lightdm ( display-manager.service ). Once I log back in, I don't have a top bar and plank ( dock ) either. I need to get a terminal and restart lightdm once again to have access to my top bar and dock ( plank ).

Please tell me if I didn't post it in the right project!

**Comment by JeffLabonte** [comment]
I will try to run it, once I switch again!

**Comment by JeffLabonte** [comment]
It works in the case I switch from intel to Nvidia, I can pop a terminal or run wingpanel and everything is up. When it comes to Nvidia to intel, I need to go in a different TTY and restart lightdm once again thru the tty

**Comment by davidmhewitt** [comment]
Due to the age of this issue, I'm going to guess this was a problem caused by Cerbere which we have since deprecated. Please re-open if you still experience this on a fully up to date system
