### ISSUE TITLE
Remove/combine Try/Install/OEM grub entries

### ISSUE THREAD

**Issue by danirabbit** [elementary/os#222]
Since this is now all one thing

**Comment by kgrubb** [comment]
The new dailies have a grub theme that says "Try or install elementary OS":

![Screenshot from 2019-10-29 23 15 06](https://user-images.githubusercontent.com/8471701/67826149-fa728a80-faa1-11e9-86f4-bfc67220de69.png)

The syslinux theme has also been updated with the same entry:

![Screenshot from 2019-10-29 23 17 15](https://user-images.githubusercontent.com/8471701/67826256-4d4c4200-faa2-11e9-8569-335d0e67f07b.png)
