### ISSUE TITLE
When I start Chrome and start typing... something automatically gets written and the PC hangs

### ISSUE THREAD

**Issue by mkniloy** [elementary/os#223]
![IMG_20190815_132016](https://user-images.githubusercontent.com/53095171/63080196-55e0b200-bf62-11e9-91e9-bd80f9df35df.jpg)

**Comment by ryonakano** [comment]
Could you provide more details, like what did you try to type?

I recommend you to attach a screencast (in GIF) in your comment using apps like [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder).

**Comment by mkniloy** [comment]
Sorry I can't seem to upload the GIF because it's too big...
I just typed "gi" and then the text on the above picture shows up...and the keyboard and mouse stops working(it also happens on epiphany browser)
After that pc automatically takes me to Chrome's settings...

**Comment by ryonakano** [comment]
Hmm… Are you using bijoyUnicode or bijoyClassic when you type?

**Comment by mkniloy** [comment]
No

**Comment by ryonakano** [comment]
Clearing histories of Google Chrome or restarting your system won't fix?

Also, does this issue only happen on Google Chrome and Epiphany? How about other entry fields like the search entry in the Applications Menu?

**Comment by mkniloy** [comment]
Restarting didn't fix it.
Yes it also happens in the search entry in the applications menu

**Comment by ryonakano** [comment]
Are your keyboard and input method engines exactly the same with the screenshot you attached at https://github.com/elementary/switchboard-plug-keyboard/issues/231?

**Comment by mkniloy** [comment]
Yes I think. I reinstalled elementary OS...after that I just tried your method to use bijoy...but that didn't work...

**Comment by ryonakano** [comment]
Ah, that's my fault… I'm sorry for the confusion.

I've just checked my method and now it should OK. Could you test whether the following way makes Bijoy available and fixes this issue?

---

- Before running the following commands, make sure to download and extract the "Bijoy Ekushe" folder.

- Open your Terminal, copy and paste the following commands:

```bash
cd Bijoy\ Ekushe
sudo cp bn-bijoy*.png /usr/share/m17n/icons
sudo cp bn-bijoy*.mim /usr/share/m17n
sudo sh -c 'echo "/usr/share/m17n/icons/bn-bijoyClassic.png\n/usr/share/m17n/bn-bijoyClassic.mim\n/usr/share/m17n/icons/bn-bijoyUnicode.png\n/usr/share/m17n/bn-bijoyUnicode.mim" >> /var/lib/dpkg/info/m17n-db.list'
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'm17n:bn:bijoyUnicode'), ('ibus', 'm17n:bn:bijoyClassic')]"
```

- Add the custom command "ibus-daemon -drx" to the startup command from System Settings→Applications→Startup
- Reboot your system. After rebooting, click "Input Method Settings…" in System Settings→Keyboard to open IBus Preferences and add bijoyClassic and bijoyUnicode in the "Input Method" tab. Now switching bijoyUnicode with Ctrl+Space should allow you to type Bengali.

**Comment by mkniloy** [comment]
I can't type anything... installing Windows 10 then I'll install elementary OS again...but I think currently I won't be able to use bijoy...until I find a flawless method of using it...
