### ISSUE TITLE
.iso build instructions

### ISSUE THREAD

**Issue by lfuelling** [elementary/os#224]
Hi,
are there any instructions available on how to build the elementaryOS `.iso` file?
The documentation on the website only covers download, installation and development of packages.

**Comment by lfuelling** [comment]
To clarify: Something like a Jenkinsfile or a Travis config would be enough for me. 
I could write a howto from that and add it to the docs.

**Comment by naftulikay** [comment]
A new ISO merits being built right now, now that HWE kernel 5.0.0 is available and stable. My hardware won't boot without this latest kernel.

**Comment by lfuelling** [comment]
Almost a month with no word by maintainers :c

**Comment by naftulikay** [comment]
I was actually able to do so and I detailed instructions [here](https://elementaryos.stackexchange.com/questions/19731/how-do-i-build-an-elementary-os-iso-manually).

In a nutshell, there is a tool called Cubic which makes building an ISO from an existing ISO super trivial. You pass it an ISO and it extracts it and opens a root shell in a chroot inside where you can update packages and modify anything in any way you'd like. I did so and simply upgraded all packages and made sure that `linux-image-generic-hwe-18.04`, `linux-firmware`, and `linux-headers-generic-hwe-18.04` were all installed and upgraded. I then rebaked the ISO and I was actually able to boot and install elementary OS without any hiccups.

It would, however, be easier to maintain the ISO if there was a GitHub repository and a defined build system. Cloning the repository, updating the build scripts, and just building from the CLI would be really helpful here and would encourage community involvement.

**Comment by lfuelling** [comment]
The application you suggested unfortunately segfaults when loading the elementary iso. 

Regardless, this issue is about creating the disk image from sources, not about customizing an existing iso.

**Comment by naftulikay** [comment]
Interesting, I had no problems on it when using it on a Loki host.

**Comment by cassidyjames** [comment]
@flexiondotorg has mentioned helping to document this process for us and any other Ubuntu-based distros. I think he's busy until the Ubuntu MATE 19.10 release, but we should see some progress after that. :crossed_fingers: 

While I'm here, I'll share the documentation we _do_ have.

- [Terraform](https://code.launchpad.net/~elementary-os/elementaryos/trunk) is something we have used. It's unclear if it's still in production.
- Building an ISO from seeds is the "correct" way to build Ubuntu and Ubuntu-based ISOs, and there is some [collected documentation](https://docs.google.com/document/d/1RPPF14h1Sw2gQjGTuZjUIlNHnGrafS8ekhFjJM9MT00/edit) from a while back.
- Ubuntu Budgie uses [iso-builder](https://github.com/UbuntuBudgie/iso-builder), which was forked from Terraform.

Cody has left elementary without any notice and without documenting these and related processes, hence the uncertainty. Sorry that this has left folks waiting so long, but we'll be able to move forward pretty quickly and have _much_ better documentation as a result. I'm confident with Martin's experience with Ubuntu MATE that we'll be able to get this sorted soon!

**Comment by naftulikay** [comment]
@cassidyjames if we're able to get it into an automated build system, it would be cool to see a new elementary ISO built on each minor release of the LTS :sunglasses:

If there's automation, should be pretty easy to setup a trigger somehow. Let me know if I can help!

**Comment by danrabbit** [comment]
Hey guys we just merged the new automated build system brand to master and the README contains build directions.

Is this issue now fixed?

**Comment by cassidyjames** [comment]
@naftulikay this one. :D

**Comment by lfuelling** [comment]
Hi, 
I tested the script and it exited with code 0 (apparently successful) but the last output was "Reading package list" and there is no `build` folder, only `tmp`.

Is there something missing in the docs or does the script only work on elementaryOS?

**Comment by cassidyjames** [comment]
@lfuelling check the workflow script, there's currently a manual step with installing the syslinux theme that has to be done on the host (it's intended to be done via CI or in a VM). We're also observing some issues once you install the built image, but now that this is documented we're working through them.
