### ISSUE TITLE
 Final "Install" slide in Elementary GUI installer doesn't feature any content. 

### ISSUE THREAD

**Issue by jebeld17** [elementary/os#225]
The final "Install" slide in the Elementary installer during a GUI install from the live .iso image doesn't feature any content.
This means there's no imagery or slide content on the last slide, which all other slides featured nice artwork. In addition, there's no indicator telling the user that they are now on the "last slide."

Bug was originally reported in Canonical's Launchpad bug tracker system at https://bugs.launchpad.net/elementaryos/+bug/1840479

**Comment by cassidyjames** [comment]
This is obsolete as the [new installer](https://github.com/elementary/installer) takes a different approach.

**Comment by jebeld17** [comment]
Then the issue is with the new installer. I just downloaded the new Juno
release and installed it on my PC, which is when I noticed this.

**Comment by jebeld17** [comment]
Sorry, I just now saw the new installer hasn't been released yet.
Why not for the time being, place at least some form of slide in the last
step on the old installer?

**Comment by cassidyjames** [comment]
@jebeld17 the refresh of the elementary ISOs will have the new installer.

**Comment by jebeld17** [comment]
But what about the time from now until then?
