### ISSUE TITLE
Include Firmware Update GUI in ElementaryOS

### ISSUE THREAD

**Issue by jebeld17** [elementary/os#226]
With firmware updates being critical for users to install to either bring new features or patch security holes, most users would benefit from having a GUI interface to scan for and install firmware updates built into part of the OS.

Ubuntu-based PopOS and System76 have a new open source GUI tool that solves this problem and can be built into ElementaryOS:
https://github.com/pop-os/firmware-manager/blob/master/README.md

**Comment by tintou** [comment]
Probably a duplicate of https://github.com/elementary/appcenter/issues/498

**Comment by jebeld17** [comment]
@tintou, it is similar, but I think System76's approach is a little better as it gives users more control over which parts to upgrade.

**Comment by cassidyjames** [comment]
@jebeld17 it's the same underlying system, pulling the same information from the same place—and we've not even designed our UI yet. How can you be sure one approach is "better" than another?
