### ISSUE TITLE
Provide libhandy

### ISSUE THREAD

**Issue by tintou** [elementary/os#228]
We can then have nice things when using it https://source.puri.sm/Librem5/libhandy
It also has a debian packaging within the source tree

**Comment by cassidyjames** [comment]
We do need to patch `src/meson.build` to depend on GTK 3.18 instead of 3.24; @Kekun said it depends on 3.24 just for some GTK styles that got into Adwaita then.

**Comment by tintou** [comment]
Now available in the elementary staging PPA

**Comment by danrabbit** [comment]
@tintou can we move this from staging into stable?

**Comment by tintou** [comment]
Currently building, it will soon be available in elementary os-patches PPA
