### ISSUE TITLE
Drop Ubuntu AccountsService patch

### ISSUE THREAD

**Issue by danrabbit** [elementary/os#229]
It sounds like users are seeing things like a `libvert-qemu` user which should be recognized as a system account and not shown. (resulting in reports like elementary/greeter#328)

According to [this answer](https://askubuntu.com/questions/897026/why-do-i-have-a-libvirt-qemu-account-in-lock-switch-account-options-in-ubuntu/940069#940069) on AskUbuntu this is a bug in accountsservice.

We should probably try to track this upstream and see if we can get a patch in and/or add a manual workaround to detect and skip users with `nologin-shell`

If we're really lazy, a hotfix for `libvert-qemu` specifically would be to blacklist UID `64055` which is the reserved user number for this in debian and Ubuntu. More details here: https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1637601

**Comment by robert-ancell** [comment]
Yes, we've just dropped the patch and no issues seen at the moment.
