### ISSUE TITLE
Firejail security sandbox desktop integration

### ISSUE THREAD

**Issue by hawake** [elementary/os#235]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Hi, i think that could be useful to provide to regular users, automatic isolation of (vulnerable) software connected to untrusted networks (i.e. browsers and so on) in the default base install of Elementary OS.

**Describe the solution you'd like**

I think that an interesting solution would be to integrate the Firejail sandbox [0] in the base OS. This kind of solution can dramatically improve security of the base OS isolating applications exposed to the network. Furthermore Firejail

- is simple to use both from CLI and from provided GUI (Firetools);
- is not performance-hungry (it is integrated in the Linux kernel);
- can be easily integrated in setup tools (i.e. we could provide not just a comfortable integration with the Desktop Environment but also an easy to use setup GUI inside the system settings window);
- supports AppImage packages.

[0] https://firejail.wordpress.com/

**Existing work**

As far as i know, there has been some kind of proposal to integrate the work already done in Ubuntu with Apparmor [1], but it is dated back in 2016.

As per Firejail, it is already included in Ubuntu/Elementary's repos (apt install firejail to obtain the 0.9.52 from Bionic).

[1] https://blueprints.launchpad.net/elementaryos/+spec/apparmor (the page report the issue as "completed" but i can't find more information).

**Describe alternatives you've considered**
Apparmor is another interesting solution, but i think it could need more work to integrate it in Elementary (correct me if I'm wrong).

**Additional context**

**Comment by danrabbit** [comment]
I think I'm inclined to close this since the current plan is to sandbox all applications using Flatpak.

Is there some specific use case that Firejail would cover that Flatpak does not?

**Comment by danrabbit** [comment]
Closing because I never got a response from OP
