### ISSUE TITLE
Epiphany should be called Web

### ISSUE THREAD

**Issue by benwaffle** [elementary/os#240]
Compared to names like Calendar, Mail, Files, Photos, etc... Epiphany is a bit confusing and should be called Web (as it is on GNOME).

**Comment by ryonakano** [comment]
Thank you for your reporting, but there seems to be an exisiting issue for this; https://github.com/elementary/default-settings/issues/96. I'll close this as a duplicate of it.

**Comment by benwaffle** [comment]
great, thanks!
