### ISSUE TITLE
Get an graphical Afremov whenever I get out of suspension

### ISSUE THREAD

**Issue by underlineGalaxy** [elementary/os#249]
Suspension on my system works really bad on my system. Pressing the off button will hibernate and most of the times actually work, but with a 10% chance that when I turn it on again the thing just stays on a black screen. Same with closing the lid.
Suspending is even worse: it does not work. At all! It gives me this beautiful piece of art whenever I do it: https://i.imgur.com/e8TqDod.jpg
The system is then non-responsive and has no visual feedback, I have to also hold the power button when something like this happens.

Reported on reddit, there was another user who had a similiar error: "I have this problem too but its limited to the top 4ish pixels and only happens for like 30 minutes after a reboot. It is a software issue because when i mouse over it my mouse is still visible."

Some other times I see only bits of that work of art when doing my stuff on the OS, it's rare and mostly happens when I am moving windows of my apps around.

**My PC specs** : Acer Aspire 5 A515-41G-13U1, AMD FX CPU with integrated graphics with also an amd gpu.

(My instincts tell me this has something to do with wine... idk)

Here are similiar issues that I found, none came to this extent however:

# Similiar:
https://github.com/elementary/gala/issues/21
https://github.com/elementary/os/issues/133

# Fix?:
https://github.com/elementary/gala/pull/330

**Comment by danrabbit** [comment]
I'm going to close this as "Out of scope" for this repository since this does not seem like an issue that can be fixed within the scope of these build scripts.

This looks to me more like a driver issue, which is Linux kernel stuff

**Comment by underlineGalaxy** [comment]
@danrabbit this is the only system which I have this issue. I used the same device with Ubuntu, qubesOS and PopOS, and I linked some similiar entries which also show other people who got this problem.

I am 50% sure this is a issue exclusive to Elementary OS, it might be out of the scope of this project but it certainly is related to the project itself.
