### ISSUE TITLE
OS7 - ubuntu security repo missing from daily iso apt sources list

### ISSUE THREAD

**Issue by vjr** [elementary/os#252]
Apparently in an installation off a distinst based ISO which I created from master there aren't any entries for the `security.ubuntu.com` repo in `/etc/apt/sources.list` just the `bionic` and `bionic-updates` portions for `main restricted universe multiverse`.

My installation off an ubiquity based ISO which I created from master seems to have the proper sources configured.

**Comment by vjr** [comment]
This appears to be an issue with Odin daily as well.

**Comment by vjr** [comment]
Revisiting this for OS7 and it appears the same issue persists - unless I'm missing something?

The `/etc/apt/sources.list` file has only the `jammy` and `jammy-updates` portions and does not pull from the `jammy-security` sub-repo.

**Comment by meisenzahl** [comment]
This is our configuration located at https://github.com/elementary/os/blob/master/etc/auto/config:

> --mirror-chroot-security "http://security.ubuntu.com/ubuntu/"
> --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/"
> --mirror-binary-security "http://security.ubuntu.com/ubuntu/"
> --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/"
> --security true

According to https://manpages.ubuntu.com/manpages/bionic/man1/lb_config.1.html we set all available parameters correctly:

##  --parent-mirror-chroot-security URL
> sets the location of the debian security package mirror that will be used to fetch the
> packages   in   order   to   build  the  live  system.  By  default,  this  points  to
> http://security.debian.org/debian/.

## --parent-mirror-binary-security URL
> sets the location of the debian security package mirror that should end up  configured
> in the final image. By default, 'http://cdn.debian.net/debian-security/' is used.

## --mirror-chroot-security URL
>  sets the location of the debian security package mirror that will be used to fetch the
>  packages  of the derivative in order to build the live system. By default, this points
> to http://security.debian.org/debian/.

## --mirror-binary-security URL
> sets  the  location  of  the  derivatives  security  package mirror that should end up
> configured in the final image.

## --security true|false
> defines  if  the security repositories specified in the security mirror options should
> be used or not.

**Comment by vjr** [comment]
Hi @meisenzahl yes it's working for me too. I did two installs of elementaryos-7.0-daily.20221107.iso in virtualbox, one direct custom install with English (UK) language and Indian (English) keyboard choice and manually creating ESP and root partitions, and the other install after going to demo mode (security repo present here too) then launching the installer and doing "erase and install" with same region/keyboard choices.
