### ISSUE TITLE
Provide "mat2"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/os#261]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Due to the old Ubuntu LTS base, elementary only has the version of "MAT" in its package sources that is no longer supported by the developer. Upgrading to "mat2" https://0xacab.org/jvoisin/mat2 would help to solve this issue https://github.com/elementary/files/issues/1030

**Comment by davidmhewitt** [comment]
We don't backport and maintain packages unless there is a very specific reason to do so. It looks as though mat2 will be available in the upcoming 6.0 release anyway.
