### ISSUE TITLE
[question] Where do current users get the info that Juno is now Hera from?

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/os#264]
The question goes specifically in the direction that the system will now be called "Hera" for users doing the regular updates. However, many of my friends are not technical users. They don't read the GitHub repo or the blog. They simply need a system that runs. As feedback I got that they didn't know that their system now has a new version.
So does it make sense to make this change/step visually understandable within the system? Also for point releases. And wasn't that actually the idea of your onboarding concept & app?

**Comment by micahilbery** [comment]
I believe in the about pane of system settings it will now say the OS is Hera if the system is up to date.

**Comment by 4jNsY6fCVqZv** [comment]
Yes, but even in "About" I never stop by as a standard user. Especially since there is no further information about new releases. Only the name changes there. I rather think about the latest news and of course a link to the great blog article. After a restart in Onboarding e.g. Or just other solutions. The issue is supposed to pave the way for discussion.

**Comment by notanimposter** [comment]
This is a good point actually. It'd probably be a good idea to alert the user somehow that the version name has changed.

**Comment by cassidyjames** [comment]
There's not really anything to act on in this report, so I'm inclined to close it. If a user does not know the code name of their OS, that's perfectly fine—in day-to-day usage, there is no reason they need to know it. If they need to know it, it's easy enough to look up in the standard "About" section as it always has been. Throwing some pop-up for all users just to tell people about a code name change would be excessive and invasive imho.
