### ISSUE TITLE
Allow to temporarily fake the distribution information to make third party software behave different

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/os#271]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
I wanted to install halyard using the installer from https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh to install halyard on my system.
But the script checked the distribution info and requires that it runs on Ubuntu > 14.04 as far as I remember. 

As elementary OS 5.1 is based on Ubuntu 18.04, I think it might work on elementary OS as well.

**Describe the solution you'd like**
I want to have an option that allows to change the commands that help identifying the current linux distro to report the underlying Ubuntu version of the elementary OS version I have installed.

**Comment by cassidyjames** [comment]
This is theoretically possible to do manually, but seems too dangerous/esoteric to be a standard feature. Instead, software can be encouraged to support elementary OS specifically, or to use the `-u` flag of lsb_release to check for upstream releases in the case of unsupported downstream releases. Several other pieces of software have done one or the other.

**Comment by CodingSpiderFox** [comment]
Thanks!
