### ISSUE TITLE
Package libportal

### ISSUE THREAD

**Issue by tintou** [elementary/os#274]
Package version 0.3

**Comment by tintou** [comment]
Now in staging: https://code.launchpad.net/~elementary-os/+recipe/libportal-bionic

**Comment by davidmhewitt** [comment]
Did this get deleted again? I can see the build succeeded, but the binary builds aren't in the staging repository.

**Comment by tintou** [comment]
It has indeed being deleted, we can rebuild it for os-patches if that is wanted for Bionic

**Comment by davidmhewitt** [comment]
I was interested in using it on focal for some testing, but could build it from source if necessary.

**Comment by tintou** [comment]
This is not useful outside of flatpak so let's not include it in the PPAs.
