### ISSUE TITLE
Allow for elementary apps to be easier to debug: enable debug symbols build on PPA

### ISSUE THREAD

**Issue by igalic** [elementary/os#276]
When an app does crash it would be nice to be able to provide better issues, or even just debug myself, I'd like to be able to install debug symbols.

Currently, they are not enabled on the PPA.

**Comment by davidmhewitt** [comment]
Debug symbols are built and uploaded to the PPA, you just have to enable the installation of them locally on your machine by following the Ubuntu guide here:
https://wiki.ubuntu.com/DebuggingProgramCrash#Installing_dbgsym_packages_from_a_PPA
