### ISSUE TITLE
Unable to build Next ISO based on focal 

### ISSUE THREAD

**Issue by Nikoos** [elementary/os#277]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Unable to build 6.0 ISO with the current configuration. it's due to a missing file : 
`/usr/share/debootstrap/scripts/focal`

In the actual Ubuntu developement version, this is a symlink from `/usr/share/debootstrap/scripts/gutsy`

After adding a quick and dirty "hack" on the build.sh script (added after line 16) : 

`cd /usr/share/debootstrap/scripts/ && ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/focal`

the build process is still in progress.

**Comment by kgrubb** [comment]
debootstrap hasn't released [1.0.117](https://salsa.debian.org/installer-team/debootstrap/blob/master/debian/changelog) yet, which contains the new focal script. It looks to just be a link to the gutsy script, so the symlink method you posted earlier should work for now. Here's the related merge request: https://salsa.debian.org/installer-team/debootstrap/merge_requests/36
