### ISSUE TITLE
elementary-live depends on fwupdate-signed

### ISSUE THREAD

**Issue by Nikoos** [elementary/os#279]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When building the 6.0 ISO at step "lb chroot_install-packages live" live-build tries to install elementary-live that has 2 unmet depenencies:

`The following packages have unmet dependencies:
 elementary-live : Depends: fwupdate-signed but it is not installable
                   Depends: ubiquity-slideshow-elementary but it is not installable
`
For the first package fwupdate-signed seems to be replaced by fwupd (https://packages.ubuntu.com/search?keywords=fwupdate)

Best regards,

Nikos

**Comment by tintou** [comment]
The package fwupdate has been renamed to fwupd so fwupdate-signed is now fwupd-signed

**Comment by davidmhewitt** [comment]
This will be resolved once https://github.com/elementary/platform/pull/4 is merged, the necessary changes to the seed files have been made, we just need to push the changes to the metapackages repository and rebuild the metapackages in launchpad.

**Comment by danrabbit** [comment]
This should now be resolved :)
