### ISSUE TITLE
Be sure of the version of Plank that is included

### ISSUE THREAD

**Issue by tintou** [elementary/os#280]
The current version included in https://code.launchpad.net/~elementary-os/+archive/ubuntu/daily/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic is 0.11.4+git20190505.96bbb1d2-0elementary5.0.1
I'm not sure that it's from https://code.launchpad.net/pantheon-dock or from https://code.launchpad.net/plank and as @ricotz is the uploader he probably has an answer to that :slightly_smiling_face:

**Comment by davidmhewitt** [comment]
I'm pretty sure that this is resolved now that we've got https://github.com/elementary/dock
