### ISSUE TITLE
NVIDIA installer spam slowing down install

### ISSUE THREAD

**Issue by beli** [elementary/os#282]
I've just installed elementaryOS 5.1 Hera, using an image I downloaded yesterday, on a machine with an NVIDIA card, and ticked the box for "Install third party software". During install, the terminal window on the installer was spammed with what seemed to be an endless loop of nvidia-nvlink messages, example - "unregistered the nvlink core". I'm pretty sure this slowed down the install - this went on even after I clicked 'Skip' until the button was greyed out. Searching the 'net, I came across what seemed to be the exact same bug on Ubuntu [fixed in March last year for 19.04] which presumably found its way into elementary: 
https://bugs.launchpad.net/ubuntu/+source/casper/+bug/1824177

### To Reproduce
1. Begin install of elementaryOS Hera on a machine with an NVIDIA GPU
2. Select "Install third party software"
3. Observe repeated 'nvidia-nvlink' messages in the terminal window

**Comment by davidmhewitt** [comment]
Current versions of elementary don't ship the Ubuntu Ubiquity based installer anymore, which is where this issue originated.
