### ISSUE TITLE
Investigate failures to install distinst in focal

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/os#283]
From the latest [build attempt](https://github.com/elementary/os/commit/5c692ffee5e817a2f8e10237dd7b9e541d6d7cd1/checks?check_suite_id=401093355) of the 6.0 iso:
```
2020-01-15T01:14:32.6171257Z The following packages have unmet dependencies:
2020-01-15T01:14:32.6822713Z  distinst : Depends: libdistinst (= 0.3.2~1565112105~18.04~b3f3276~dev) but it is not going to be installed
```

Unfortunately there isn't any more detail, but I would assume this is because it's an 18.04 package that's been copied in and probably depends on something we don't have anymore.

It may turn out that this is a wider piece of work to try and get the installer up to date with the recent Pop changes so we can use a newer distinst, but may be worth having a go at building a focal version of the same distinst commit to try and get us off the ground for now.

**Comment by Nikoos** [comment]
Hi @davidmhewitt ,

After some research on libdistinst issue, I have some info to share :

`(live)root@f1ef8218714f:/# apt policy libdistinst
libdistinst:
  Installed: (none)
  Candidate: 0.3.2~1565112105~18.04~b3f3276~dev
  Version table:
     0.3.2~1565112105~18.04~b3f3276~dev 500
        500 http://ppa.launchpad.net/elementary-os/daily/ubuntu focal/main amd64 Packages
(live)root@f1ef8218714f:/# apt install libdistinst
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdistinst : Depends: btrfs-tools but it is not installable
E: Unable to correct problems, you have held broken packages.
(live)root@f1ef8218714f:/# apt search btrfs-tools
Sorting... Done
Full Text Search... Done
`

Moreover, when searching the package in Ubuntu packages website, we got the following link : 
[https://packages.ubuntu.com/search?keywords=btrfs-tools](https://packages.ubuntu.com/search?keywords=btrfs-tools)

If we try to search for this btrfs-tools package in focal : 
[https://packages.ubuntu.com/search?suite=focal&keywords=btrfs-tools](https://packages.ubuntu.com/search?suite=focal&keywords=btrfs-tools)

This package does not exists and should be replaced by btrfs-progs (if I am correct).

Regards,

Nikos

**Comment by davidmhewitt** [comment]
This has been resolved by importing a newer version of distinst from the pop-os ppa.
