### ISSUE TITLE
Switchboard should conflict with switchboard-plug-gcc-* packages

### ISSUE THREAD

**Issue by codygarver** [elementary/os#29]
Must ensure clean upgrade for Switchboard plugs since old Color, Sound and Wacom will be gone for Juno.

**Comment by cassidyjames** [comment]
@codygarver is this a blocker for the beta? We haven't committed to upgradability, especially to a beta release. And considering the large amount of TODO items on https://github.com/orgs/elementary/projects/20, I don't see this being feasible for the 5.0 release anyway.

**Comment by danrabbit** [comment]
Gonna move this to Switchboard since deb packaging is on GitHub now

**Comment by danrabbit** [comment]
Closing since we released Juno and never did this.. or maybe we did? I dunno. Either way it's no longer relevant
