### ISSUE TITLE
VMWare Workstation & Pantheon on Debian 10

### ISSUE THREAD

**Issue by iDustbin** [elementary/os#294]
Hi, maybe its the wrong repo but im running into an "pantheon" issue.

Whats happend:
Debian 10 
Pantheon Desktop
VMWare Workstation

Mostly is working fine, i can use vmware by tools and utils like. Vagrant, Packer or Terraform.
vmrun is working fine

My Issue: 
If im try to install an Windoof VM then i need an gui integration,
i can open vmware-workstation but the vm screen is "black"

how can i solve my issue. is there any libary missing ? 
missing 3d acceleration

**Comment by cassidyjames** [comment]
It's really hard to know what the issue could be, especially when not on elementary OS. I would recommend you head to a community support site like https://elementaryos.stackexchange.com to ask if others might know what's going on.
