### ISSUE TITLE
Spin January, 2020 Hera ISO

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#295]
Now that kernel 5.3 and all the new LTS bits are out, we need to spin a new ISO for hardware compatibility. It will also be nice to include all the releases from the month of January when we mention the new spin in the January updates post.

**Comment by davidmhewitt** [comment]
Should just be a case of pushing a tag when ready and GitHub actions will do its thing.

**Comment by kgrubb** [comment]
Release: https://github.com/elementary/os/releases/tag/5.1.1
ci run: https://github.com/elementary/os/runs/417675698

__TODO:__

- [ ] generate torrent files
- [ ] update website with new iso & sha

**Comment by J0Ar** [comment]
@kgrubb  The website still shows the old sha. Maybe someone can take a look at this?
I think it should be **190bbf738db0f15daa9ee4095bb64c307950082819081a969f8edd51f1faab07**

![Bildschirmfoto von 2020-02-07 19-33-56](https://user-images.githubusercontent.com/23266409/74055971-502fca80-49e1-11ea-9199-c3bde78e75bb.png)
