### ISSUE TITLE
Minimize button because just learned that adding it with Tweaks can compromise my system!

### ISSUE THREAD

**Issue by spirulin** [elementary/os#299]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Just saw this post and learned that adding PPA can be dangerous:
https://www.reddit.com/r/elementaryos/comments/f1b0tj/we_want_eos_to_be_as_secure_as_possible_but_they/
I agree with the OP without the rude part.
I am one of the users that after fresh install the first thing I do is to download the Elementary Tweaks and add the minimize button because this is how I am used to using my PC and I find it very difficult to operate without it and to be honest I really don't understand how someone could do it without it. Keyboard shortcuts are not like a mouse click. I had no idea before reading the post that the PPA added from somewhere that's not really checked by You guys can be bad for privacy and security and I am kinda all about those two and right now I am not sure I want to keep using Elementary as my Linux choice. I don't add anything that's not in the AppCenter to my system again for security reasons. Thought Tweaks was made from someone from the Elementary team but turned out it's from someone that's not from the team.
One of the things I love about Elementary is it's focus on security even installing Flatpaks gives you a warning that it may not be secure to install apps from there.

**Describe the solution you'd like**
To add somewhere in the Settings optional setting to add minimize button or make Tweaks part of the OS.

**Existing work**
No minimize button and need to add the Tweaks from who knows what else will come from the PPA.

**Describe alternatives you've considered**
Add Tweaks in the OS or add the option to add the minimize button in the Settings.

**Additional context**
You add so many different things why not add one thing that most users Add anyway after installing the Elementary OS? I know you see it somehow different but it's not in a good way different. You want it to be easy to use OS and most of the time it really is a noob-friendly experience but just imagine like right now Windows 7 users are looking for Linux OS coming for Elementary OS and having to deal without Minimize button something they are used to and not having an idea about keyboard shortcuts and workspaces that are not convenient at all for the regular user.

**Comment by tintou** [comment]
We are not supporting the minimize behavior you're underlying by design. See this blog post for the reasoning: https://blog.elementary.io/what-still-up-with-window-controls/
