### ISSUE TITLE
Unable to remove packages in chroot

### ISSUE THREAD

**Issue by kgrubb** [elementary/os#300]
**Describe the bug**
6.0 daily images fail to install due to a chroot error when purging packages:

<img width="189" alt="Screen Shot 2020-02-12 at 5 28 03 PM" src="https://user-images.githubusercontent.com/8471701/74383989-50074480-4dbe-11ea-989d-d6589a915613.png">

**To Reproduce**
1. Download the latest 6.0 daily image
1. Burn it onto a usb and boot from the usb (or insert the disk in a vm manager and start the vm)
1. Select your language and keyboard layout
1. Select "Clean Install":
	<img width="401" alt="Screen Shot 2020-02-12 at 5 39 18 PM" src="https://user-images.githubusercontent.com/8471701/74384127-a2486580-4dbe-11ea-8232-27a8717bcc41.png">
1. Select a drive and click "Erase and Install"
1. Select "Don't Encrypt"
1. The installer should error and provide the following output via the `Details` button.

**Comment by kgrubb** [comment]
Looks like one of these packages is the culprit:
```
INFO: running "chroot" "/tmp/-distinst.i58lEWCNKbzz" "apt-get" "purge" "-y" "adwaita-icon-theme-full" "btrfs-progs" "casper" "cifs-utils" "discover" "discover-data" "distinst" "dmraid" "elementary-live" "expect" "f2fs-tools" "fatresize" "finalrd" "gettext" "gparted" "gparted-common" "io.elementary.installer" "io.elementary.installer-session" "kpartx" "kpartx-boot" "libatkmm-1.6.1v5:amd64" "libcairomm-1.0.1v5:amd64" "libdiscover2" "libdistinst" "libdmraid1.0.0.rc16" "libf2fs-format4:amd64" "libf2fs5:amd64" "libglibmm-2.4-1v5:amd64" "libgtkmm-3.0-1v5:amd64" "libnss-mymachines:amd64" "libpangomm-1.4-1v5:amd64" "libsigc+-+-2.0-ov5:amd64" "libtcl8.6:amd64" "libusb-0.1-4:amd64" "localechooser-data" "mokutil" "reiserfsprogs" "systemd-container" "tcl-expect:amd64" "tcl8.6" "user-setup" "xfsprogs" "kernelstub"
```
<img width="186" alt="Screen Shot 2020-02-12 at 6 15 22 PM" src="https://user-images.githubusercontent.com/8471701/74386645-7d56f100-4dc4-11ea-875d-6fc1a1c4abeb.png">
<img width="185" alt="Screen Shot 2020-02-12 at 6 14 46 PM" src="https://user-images.githubusercontent.com/8471701/74386644-7cbe5a80-4dc4-11ea-9298-bdac0409cabb.png">
<img width="186" alt="Screen Shot 2020-02-12 at 6 13 47 PM" src="https://user-images.githubusercontent.com/8471701/74386641-7cbe5a80-4dc4-11ea-85bf-51c934f687a2.png">

**Comment by kgrubb** [comment]
alright, looks like `xfs-progs` and `kernelstub` are the culprits:

<img width="333" alt="Screen Shot 2020-02-12 at 6 33 25 PM" src="https://user-images.githubusercontent.com/8471701/74387321-37029180-4dc6-11ea-8af9-325586583fbc.png">

**Comment by davidmhewitt** [comment]
I've opened an issue against distinst here:
https://github.com/pop-os/distinst/issues/207

The attempted removal of `kernelstub` is a hardcoded thing in distinst and it's not a package we even ship in elementary currently.

**Comment by davidmhewitt** [comment]
This should have been resolved by https://github.com/pop-os/distinst/pull/211

We should be able to close this after confirming the fix in the next iso build to incorporate the newer version of distinst
