### ISSUE TITLE
Make Updates beautiful

### ISSUE THREAD

**Issue by linuxr01** [elementary/os#303]
## Prerequisites
- [ x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
The update process should be made nicer.

**Describe the solution you'd like**

<img width="717" alt="grafik" src="https://user-images.githubusercontent.com/49744994/75097258-e39ff880-55a8-11ea-8ae8-3a4f219eefce.png">

![grafik](https://user-images.githubusercontent.com/49744994/75097266-fe726d00-55a8-11ea-9085-54ea48cf6153.png)

Existing work:
https://gitlab.gnome.org/Teams/Design/os-mockups/blob/master/boot/boot-progress.png

**Comment by cassidyjames** [comment]
We don't install updates in an offline environment, so this is not really relevant to elementary OS.
