### ISSUE TITLE
focal can fail to boot due to waiting on dev-mapper-cryptswap start job

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/os#307]
Experienced this on the 2nd boot of a clean focal daily install. All I'd done was install my WiFi drivers and rebooted, although I suspect this was unrelated. It would seem there's a random chance of this happening on every boot, but is worse on some hardware than others.

The same issue has been reported against Pop!_OS here: https://github.com/pop-os/pop/issues/316

Using the recovery mode to apply the workaround described here has resolved the issue on my machine:
https://github.com/pop-os/pop/issues/316#issuecomment-514316415

It looks as though this is an issue in systemd and Pop!_OS have resolved it by patching the workaround into systemd, but the patch hasn't been accepted upstream due to it being a workaround and not a fix for the root cause.

**Comment by davidmhewitt** [comment]
Got this again today on a fresh install of the daily 6.0 iso.

**Comment by davidmhewitt** [comment]
It looks as though this was fixed in systemd and then Ubuntu have applied a backported patch as of the end of July:
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1838329

I'll do a clean install on my laptop that consistently reproduced this soon and see if I get it again. But hopefully this is fixed and we can just do nothing.

**Comment by meisenzahl** [comment]
@davidmhewitt is this still an issue?

**Comment by davidmhewitt** [comment]
I haven't seen it so let's close the issue!🎉

Can always reopen it if someone else experiences it.
