### ISSUE TITLE
Can we please fix the emacs GUI version?

### ISSUE THREAD

**Issue by fabianthoma** [elementary/os#31]
Emacs is one of the very very fe programs that insists on an old gtk2 bug beeing fixed, that everyone else was doing a workaround for ... So we need to set an environment Variable to fix this:

    XLIB_SKIP_ARGB_VISUALS=1

Can we please add that to our session and have this problem finally be solved? I'm available for testing and anything you need :wink:

**Comment by rafaelcn** [comment]
It's better, as a workaround, to set the `.desktop` set that for you and create an alias to open Emacs GUI in runtime correctly, that's what I've been doing.

**Comment by danrabbit** [comment]
I'm going to close this issue for elementary OS since it seems like the solution is either for emacs to provide a workaround, an unmaintained toolkit to be updated, or Ubuntu to carry a patch. Since elementary doesn't provide this package, this is "Out of Scope"
