### ISSUE TITLE
It's 2020 - Let stop shipping Python 2.7

### ISSUE THREAD

**Issue by ToroNZ** [elementary/os#321]
## Prerequisites
- [* ] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Frustrating to Install the latest version of the OS and find Python 2.7 as default python version.

````
$ python -V
Python 2.7.17
````
**Describe the solution you'd like**

Move on, ship python3.
**Existing work**

**Describe alternatives you've considered**

**Additional context**

**Comment by tintou** [comment]
We are based on Ubuntu 18.04, on next version this should be the case.
Anyway, using the unversioned python version is deprecated, you should explicitly use `python3` when executing it or in your scripts.
