### ISSUE TITLE
Battery low indication 

### ISSUE THREAD

**Issue by swaroopchirayinkil** [elementary/os#326]
In elementaryOS when the battery get's low I'm not getting any indication regarding the the low battery status.

Some times the laptop just turns off and then only I find out the battery fully drained.

OS details
-----------------
elementary OS 5.1.3 Hera
Built on Ubuntu 18.04.3 LTS
Linux 4.15.0-91- generic
GTK 3.22.30

Machine details
--------------------------
Dual-core Intel ®Core™i5-7200U CPU @2.50GHz
Intel Corporation HD Graphics 620 (rev 02)
4.0 GB memory

**Comment by cassidyjames** [comment]
elementary OS does send a low and critical battery notification. It's possible if you're not getting those that your battery itself has degraded to the point where it is not reporting acccurate data to the operating system. You can see some more information about your battery by running `gnome-power-statistics` from the Terminal.

**Comment by agrawalsourav98** [comment]
Yeah, so it turns out i had DND turned on my notifications. So, can this feature be added so that the battery low notification bypasses the DND feature? Thanks for the info @cassidyjames
