### ISSUE TITLE
Elementary Tweaks baked in the OS.

### ISSUE THREAD

**Issue by spirulin** [elementary/os#347]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
I just want to be able out of the box to change Single click opening stuff and enable Minimize and Maximize buttons without adding PPA that can be dangerous and not checked by your team. Being able to change themes and Icons is a big plus too. It already exists and working great so don't see any reasonable reason not to be included. It's not like you are going to code it by yourself. Maybe 99% of the people using your OS are installing it which puts them in possible security and privacy danger.

**Describe the solution you'd like**
Elementary tweaks to be included in the settings by default.

**Existing work**
It exists as PPA.

**Describe alternatives you've considered**
No need for alternative just Tweaks added to the settings.

**Additional context**

Daniel told us on Reddit to post about this stuff so you can add them. So this is what I am doing and hope it won't get Closed without any consideration. After all, this was suggested by the Founder of the OS.

**Comment by davidmhewitt** [comment]
Dan didn't say ask for Tweaks to be included. He said to file specific issue for _individual settings_ that you feel are missing from the OS.

Reference:
https://www.reddit.com/r/elementaryos/comments/gdfeqz/elementary_tweaks_on_eoss_future_releases/fphn84f?utm_source=share&utm_medium=web2x
