### ISSUE TITLE
Daniel said ask for it: Most of us WANT Minimize button!

### ISSUE THREAD

**Issue by spirulin** [elementary/os#348]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

The problem is your team forcing us to use the OS the way you want us to use it although it makes it 1000000 times harder to use it your way, than what would be convenient for us.
Keyboard shortcuts are not faster and will never be faster than muscle memory and mouse! 
Try using keyboard shortcuts in the dark or when you are not over your keyboard and looking at the keys!
8 of 10 times you will press something else! So what's faster? Me pointing with the mouse and clicking the button, or you trying to find 2 or 3 keys?
Or me going with my mouse to the bottom, waiting for Plank to show up because it auto hides when there is an open window, clicking on the app/program and this way minimizing it?
Don't you really see how ridiculous is what's written in the Blog post "Why there is no minimize button".
Because ONE person thinks it's better doesn't give the right to make a thousand or more people using it that way, when there is a simple solution. Especially on Linux where customization is so easy to be added. 
Elementary tweak solves the problem but it's unsecure to add PPA that is not checked by Elementary team. The same reason you are showing the Warning window for Non-cureted apps/program in the App Center! So if you care about our security so much why 99% of your users have to add a PPA that one day can put them at security risk? Ship your OS the way you want by default but give us the option to make it more friendly for our use.

**Describe the solution you'd like**
In the setting simple option to turn on Minimize and Maximize buttons.

**Existing work**
Elementary tweaks makes it better but adding someone's PPA is dangerous even if it's on GitHub or whatever. You never know what actually is being installed or how it will change in the future.

**Describe alternatives you've considered**
Elementary tweaks included out of the box but it was denied here.

**Additional context**
For reference: https://www.reddit.com/r/elementaryos/comments/gdbo1k/tried_using_elementary_as_intended_without_any/
Most of the people who use your OS are installing tweaks to solve this problem. And most of them want it out of the box as an option. So maybe it's time to stop trying to be Apple or Windows and forcing people to use something the way YOU want it and give a simple option to make it the way people want it. It's not a major change or something. Just a simple solution.

**Comment by lewisgoddard** [comment]
I guess the relevant blog links are:
- [What's Up With Window Controls?](https://blog.elementary.io/whats-up-with-window-controls/)
- [What's (Still) Up With Window Controls?](https://blog.elementary.io/what-still-up-with-window-controls/)

**Comment by spirulin** [comment]
> I guess the relevant blog links are:
> 
> * [What's Up With Window Controls?](https://blog.elementary.io/whats-up-with-window-controls/)
> * [What's (Still) Up With Window Controls?](https://blog.elementary.io/what-still-up-with-window-controls/)

**Note: this post was written over two years ago. The information below may be outdated.**
On the top. And actually more than 7 years ago. And the information was never relevant. I think Daniel was too young when he wrote it and thought he may be the next Inventor or something and changing people's lives and habits or whatever. Hope now when he is a grown-up person his attitude is different and he realized that it won't be the next big thing and it's better to make your users happy than being so self-absorbed and forcing them using it the way you want them to use it.

**Comment by cassidyjames** [comment]
If you feel like you want/need minimize, there are still ways to do so on elementary OS today (clicking in the dock, using keyboard shortcuts, or using the context menu in the titlebar). But the ship has sailed on adding a "minimize" button to titlebars because apps designed for elementary OS don't need it, and we don't cater to non-native apps.

**Comment by Stabsy** [comment]
> 
> 
> If you feel like you want/need minimize, there are still ways to do so on elementary OS today (clicking in the dock, using keyboard shortcuts, or using the context menu in the titlebar). But the ship has sailed on adding a "minimize" button to titlebars because apps designed for elementary OS don't need it, and we don't cater to non-native apps.

If you don't cater to non-native apps, you should atleast actually OFFER Apps that fit with your ideas
BUT YOU EFFING DONT.
Talk about being arrogant asshats.

**Comment by Julian-MJK** [comment]
A majority of your users almost certainly rely heavily on "non-native" apps, this is Linux after all, and the native apps don't fill the needs of all users.

The addition of minimize button could significantly improve the workflow and ease-of-use for many users, is the fact, without at all diverging from the design principles & philosophies that make Elementary OS great.

**Comment by alextrayanov** [comment]
> If you feel like you want/need minimize, there are still ways to do so on elementary OS today (clicking in the dock, using keyboard shortcuts, or using the context menu in the titlebar). But the ship has sailed on adding a "minimize" button to titlebars because apps designed for elementary OS don't need it, and we don't cater to non-native apps.

Most of the users install third party applications immediately. You native apps can't compare to VLC and real music player. None of them can. 
Not to mention you Browsers that sucks in every possible way and I would be surprised if even 1% of your users are using it.
So you are very wrong.
And as the OP described clicking on in the dock requires more steps and time than with Minimize button. Shortcuts too. So don't give such a dumb suggestions that don't work better than clicking dedicated button with a mouse.
Your and your team attitude is very arrogant.
But when asking for money to support you or your projects you are one of the nicest people.
"We want to improve people's experience".
What a bullshit. If you want to improve the experience you would add a SINGLE line of code and enable the Minimize and Maximize button even if it's in the Settings and your OS ships without them enabled which will change nothing for you. Whoever wants to use it the way you want them to use it will do so. For the rest of the people they will enable them without installing third-party tweaks (where most new to Linux will have no idea about) and enjoy the OS.

**Comment by jantari** [comment]
If you don't cater to non-native apps why did you add flatpak-integration to the appcenter? lol, if you just personally hate minimize buttons so much you don't want them in the OS it's easy enough to admit - but that sounds like a weird excuse

**Comment by Gabriel-p** [comment]
@cassidyjames you should probably just close this thread to comments. Nothing good will come out of this.

**Comment by alextrayanov** [comment]
> @cassidyjames you should probably just close this thread to comments. Nothing good will come out of this.

Cut the free speech?
Maybe you should close your account?
Something good will come when they realize that their way is not the right way.

**Comment by cassidyjames** [comment]
Thanks for the feedback, but this is an issue tracker—not a discussion forum. It wastes everyone's time to notify developers and designers of new comments, especially when they're extremely disruptive, abusive, and in violation of the [Code of Conduct](https://elementary.io/code-of-conduct). Since there is no action to be taken here, I'm locking this from further discussion. Feel free to discuss this in a more appropriate location.

**Comment by danrabbit** [comment]
I'd like to be really clear that our policy is not to lock threads where there are dissenting opinions. Respectful debate is healthy and important. But when you start calling names and being disrespectful and disregarding the code of conduct, the discussion becomes unproductive. This kind of destructive behavior is not tolerated in our community.
