### ISSUE TITLE
Noisy Screen

### ISSUE THREAD

**Issue by xunilarium** [elementary/os#350]
As Elementary OS kernel was updated to 5 my laptop screen become noisy, I tested with Windows and it works fine so my graphic card is OK.
![photo_2020-05-07_17-41-26](https://user-images.githubusercontent.com/10381709/81329835-5d2d8a00-90b4-11ea-91ca-82e2e9b0ddca.jpg)
![Screenshot from 2020-05-07 21-37-57](https://user-images.githubusercontent.com/10381709/81329854-64549800-90b4-11ea-8692-a6806c75c9c3.png)

**Comment by hanaral** [comment]
Are you able to boot in to an older kernel from grub? Also this is the issue tracker for the elementary ISO, you should ask kernel related issues on reddit or another community backed site

**Comment by xunilarium** [comment]
I don't have an older version but I tested with ubuntu 18.04.02 and every this was okay. I also posted this issue in some other community like reddit and slack exchange but no luck so far. please help me with that if you can. I tested some recommendation and this is the result:

**Ubunut 18.04.02:**
------------------------------------------------------------------------------------------------------
**Kernel Ver:** 4.18.0-15-generic
**VGA Driver:** 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620/M82 [Mobility Radeon HD 3450/3470]
Subsystem: Sony Corporation RV620/M82 [Mobility Radeon HD 3450/3470]
Kernel driver in use: radeon
Kernel modules: radeon
**Screen Status:** OK
___________________________________________________________________________________________
**Ubuntu 18.04.03:**
------------------------------------------------------------------------------------------------------
**Kernel Ver:** 5.0.0-23-generic

**VGA Driver:** 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV620/M82 [Mobility Radeon HD 3450/3470]
Subsystem: Sony Corporation RV620/M82 [Mobility Radeon HD 3450/3470]
Kernel driver in use: radeon
Kernel modules: radeon
**Screen Status:** Noisy

**Comment by hanaral** [comment]
You might want to look in to rolling back your kernel then, if that is possible

**Comment by xunilarium** [comment]
It's not possible bucause I clean installed the last version. I tried a samsung monitor with vga output on my laptop and the screen was fine on samsung monitor but noisy on laptop monitor.

**Comment by davidmhewitt** [comment]
This sounds like a linux kernel driver issue.

We ship completely unmodified Ubuntu kernels, so issues like this would need reporting to the Ubuntu linux kernel bug tracker. Closing as there's nothing we can do here
