### ISSUE TITLE
Can not receive or send file via Bluetooth

### ISSUE THREAD

**Issue by ghost** [elementary/os#351]
Can not receive or send file via Bluetooth
No options/settings for Bluetooth
Missing sharing option

**Comment by riker09** [comment]
Yeah, me too. It's 2022 and I'm missing a "Send file via bluetooth". I was surprised that this feature is missing. I tried `blueman-sendto` but the dialog keeps erroring out on me. With no useful error message I want to add.

**Comment by jeremypw** [comment]
There is a PR to fix this https://github.com/elementary/wingpanel-indicator-bluetooth/pull/130.  Hopefully it can be merged before too long.

**Comment by asadul04** [comment]
Same here.
