### ISSUE TITLE
Consider adding a system-wide autocorrect tool.

### ISSUE THREAD

**Issue by kepler-dslr** [elementary/os#357]
As a Windows and Mac OS alternative, it should have this. With some settings like dictionaries under the keyboard preferences. Just an idea.

**Comment by danrabbit** [comment]
This is something that needs to be done at the Toolkit level. You can track the relevant issue in Gtk here: https://gitlab.gnome.org/GNOME/gtk/-/issues/274

Closing as "Out of scope"
