### ISSUE TITLE
USB writter / USB formatter 

### ISSUE THREAD

**Issue by spirulin** [elementary/os#375]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
Can you add Mint Stick USB writer and USB formatter? It's very handy and there is no easy way to format or write USB without a guy. You can use the terminal but it's a lot more complicated. Or if you can create your own tool doing the same would be great as long as it has a gui and these to options.

**Describe the solution you'd like**
Program or programs with gui to be able to format or write a USB without trouble.

**Existing work**
Terminal

**Describe alternatives you've considered**
Mint stick package included out of the box or your own version of them.

**Comment by ryonakano** [comment]
We already have [a USB formatter](https://appcenter.elementary.io/com.github.djaler.formatter/) and [writter](https://appcenter.elementary.io/com.github.artemanufrij.imageburner/) designed for elementary OS. I guess this should be counterparts of Mint Stick USB Writer and USB formatter.
