### ISSUE TITLE
Desktop Session Crashing to Login Screen

### ISSUE THREAD

**Issue by justledbetter** [elementary/os#377]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
I've had issues over the past month with my desktop crashing and returning me to the login screen.  Over the past two weeks, this is happening fairly constantly, after as little as 5 minutes of use.  (On average, it takes about a half hour or so.)

### Expected behavior
Be able to use my desktop without having to re-open everything every time it crashes.

### Screenshots or screen recordings
I can try and capture a cell phone video of this happening if anyone wants to see it.  I'm not doing anything unusual before it happens.

### Logs
The only thing I can find that might be related to the problem is the following message in /var/log/syslog:

```
Jul  3 15:03:31 host kernel: [   24.793216] show_signal_msg: 9 callbacks suppressed
Jul  3 15:03:31 host kernel: [   24.793218] io.elementary.c[1947]: segfault at 0 ip 00007fd5fb216ff9 sp 00007ffe55d21ac0 error 4 in libgtk-3.so.0.2200.30[7fd5faf33000+6f1000]
Jul  3 15:03:31 host kernel: [   24.793223] Code: 5c 41 5d c3 0f 1f 00 66 2e 0f 1f 84 00 00 00 00 00 8b 35 92 20 62 00 31 d2 31 c0 e9 91 1b da ff 90 53 48 89 fb e8 47 fe ff ff <48> 8b 3b 48 89 c6 e8 4c 0b da ff 48 8b 40 18 48 85 c0 74 06 48 89
```

## Platform Information
- OS: elementary OS
- OS Version: 5.1.6 Hera
- Kernel: Linux 5.3.0-62-generic
- GTK: 3.22.30
- CPU: Intel Core i7-1065G7
- RAM: 16 GB
- Disk: 100gb free out of 500gb

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
When this happened to me the first few times, I was running on an older laptop with a 7th gen Core i7 and 8gb of RAM.  I assumed it was some kind of memory issue, but the problem persists after a fresh install on this new laptop.

I spend most of my time in web browsers (Chrome, Brave, and occasionally Epiphany) and the Terminal developing software.  Problem does not seem to be any worse when I'm compiling code, and I am not seeing anything that indicates I'm running out of memory.

Any advice on how to gather additional debugging for this weird problem, or if I should open this with a different project, please let me know!

**Comment by hanaral** [comment]
The most common reasons are either the home directory running out of space or people uninstalling a library that the desktop has as a dep. 

Looking at your log it might(?) have something to do with your hardware and the kernel. Do you have any other hardware it does this on?

**Comment by justledbetter** [comment]
Appreciate the response!

I'm not seeing anything that looks application-related in my logs, other than what I've pasted above.  I also have a Huawei laptop with a 7th gen Core i7 that exhibits the same behavior.  Both systems have plenty of free space; If it helps, it seems to generally get triggered while I'm in the middle of keyboard-based window management functions (alt-tab, bring up Applications menu, etc).

**Comment by davidmhewitt** [comment]
I'm going through and cleaning up old issues on this bug tracker.

If you're still using elementary OS and still experiencing this issue, I would suggest opening a new issue at https://github.com/elementary/gala (the window manager), as it sounds plausible from your description that this crash occurs there. 

As this repository is for the scripts that build the elementary OS .iso images, I'm going to close this as out of scope.
