### ISSUE TITLE
ElementaryOS 6 live-usb not booting

### ISSUE THREAD

**Issue by Cogitri** [elementary/os#402]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Hello,

when trying to boot from the live USB stick for Elementary OS6 I only get a blackscreen after grub. I tried booting with the following images:

```
 elementaryos-6.0-daily.20200915.iso
 elementaryos-6.0-daily.20201007.iso
 elementaryos-6.0-daily.20201008.iso
```

Tested writing the image with both dd or the Fedora Image Writer. 

### To Reproduce.
1. Plug live usb into the laptop
2. Start laptop
3. Elementary OS logo is shown with a "press e to edit, c for console" (so GRUB)
4. After the 10 seconds have passed or after pressing enter the screen stays dark forever. Since the laptop turns of immediately after pressing the powerbutton (without holding it down), I think it's still in EFI mode and hasn't actually loaded the kernel and started.

### Expected behavior
After 4. the system should start up
### Logs

Unfortunately no logs are printed to the screen, even when removing `quiet splash` from the kernel cmdline. FWIW `nodemoset` hasn't helped either.

## Platform Information

I tested this on a HP Spectre x360 - 15-ch032ng. It has an `Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz` CPU and both an Intel iGPU and an AMD dGPU. I'm currently running Linux on it (Alpine Linux) and before that I also tried Fedora and Ubuntu, which both boot just fine from the live USB. Elementary OS 5.1 also boots just fine.

**Comment by Cogitri** [comment]
Hmmm, on my desktop the image works (A Ryzen 3950X and a 570X Asus mainboard), so this might be some oddity in HP's UEFI - but considering that Elementary 5 worked just fine I suppose it's best to not close this

**Comment by keanuk** [comment]
I have the same issue on a Lenovo Yoga 920. I tested the same live USB drive on an HP laptop which did not exhibit the same problem.

**Comment by ijiki16** [comment]
Try change some bios settings.

**Comment by keanuk** [comment]
> Try change some bios settings.

I have secure boot turned off, not really sure what else there is in the BIOS that could be effecting it. I don't have any problems booting other distros off a live USB either.

**Comment by ijiki16** [comment]
what about ElementaryOS 5.1?

**Comment by keanuk** [comment]
> what about ElementaryOS 5.1?

5.1 boots without any issues

**Comment by ijiki16** [comment]
Have you tested new builds? I have build iso with docker and it worked.

**Comment by keanuk** [comment]
Yeah, I've been testing them every few weeks since they were first announced. The latest one I tested was 20210115.

**Comment by VikkieViktor** [comment]
I have the same issue but with 5.1

**Comment by KarkanAlzwayed** [comment]
I've experienced this issue on my  Dell xps 15 7000 series with hybrid graphics, but only when I boot using Legacy. It booted after I switched to UEFI. It did throw a couple of errors (that I don't remember) but it ended up booting just fine.

**Comment by elSolus** [comment]
Hey, @ryonakano I see 6.0-rc2 was released. But there are only two "assets", no iso file. Where would I find the release candidate?? (Sorry, this is the closest I could find to "asking a question" place.)

**Comment by cassidyjames** [comment]
We’re centralizing these reports into one triage: https://github.com/elementary/triage/issues/74
