### ISSUE TITLE
Wrong url in elementary.list and patches.list files

### ISSUE THREAD

**Issue by zaulychny** [elementary/os#406]
[https://bugs.launchpad.net/elementaryos/+bug/1629646](https://bugs.launchpad.net/elementaryos/+bug/1629646)

I confirm that issue described under the URL above still reproducible and requires attention as it affects all EOS team efforts.
See my last comment on the launchpad.net:

```
This bug is very bad as it spoils/ruins all work of the Elementary OS team. Impact => Any installed OS just never get updates...

On my opinion, it must be fixed asap. Note, After my manual fix of the files as explained above I got 45 components updated! Surprise, I do apply updates every few days and I never suspect that messages about some "missing PPA" were just about all Elementary OS stuff... I'm new to PPA but now lessons learned.
```

Fix as I see it => Deliver a patch which updates mentioned PPA sources in the distro images to refer  Ubuntu codename, not Elementary OS current name (e.g. _Hera_ must be replaced by _bionic_ in the files 
```
/etc/apt/sources.list.d/elementary.list
/etc/apt/sources.list.d/patches.list
/etc/apt/sources.list.d/appcenter.list
```
)

**Comment by cassidyjames** [comment]
This is a bug we have not been able to reliably reproduce in the Ubuntu Ubiquity installer, which elementary OS 5.x and earlier used. In elementary OS 6 we are using a new installer which does not have this bug.

**Comment by zaulychny** [comment]
Ok, thanks. I recall that error message about bad PPA source started to pop up after I installed slack and chrome on my EOS laptop.. Maybe it  can help you to try reproduce again...

I'm fine now after manual fix of the files above. Just FYI => I was wondering why I got some little updates to my EOS but this issue was the root cause. 

Thanks anyway for your help.
