### ISSUE TITLE
Epiphany Flatpak filter file permissions prevent rootless `flatpak update`

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#410]
The (permissions on the) filter from #403 seem to be preventing rootless `flatpak update`. It might also affect Flatpak updates in AppCenter.

```
cassidyjames@elementary-os:~$ flatpak update 
Looking for updates…
error: Failed to load filter '/etc/flatpak/epiphany.filter': Error opening file /etc/flatpak/epiphany.filter: Permission denied
```

```
cassidyjames@elementary-os:~$ sudo flatpak update 
Looking for updates…


        ID                                              Branch            Op           Remote            Download
 1.     org.freedesktop.Platform.VAAPI.Intel            20.08             i            flathub           < 11.2 MB
 2.     org.freedesktop.Platform.openh264               2.0               i            flathub            < 1.5 MB

Proceed with these changes to the system installation? [Y/n]: 
```

In this case, I don't see any updates in AppCenter, so I would assume AppCenter is hitting the same issue.

**Comment by davidmhewitt** [comment]
Ah oops, I'm an idiot. Folders need an "execute" permission to open them. We should set 644 on the file and 755 on the folder. They're probably right by default tbh, I'm not at a pc, but I'd be tempted to try a build without the chmod line.
