### ISSUE TITLE
Build failing on Debian (Docker image and VM)

### ISSUE THREAD

**Issue by manub23** [elementary/os#419]
The build system fails by throwing an error `unable to locate package xserver-xorg-hwe-20.04` while executing `lb chroot_install-packages install`.

Issue reproducable by running the Docker image on elementary OS 5.1.7 Hera as shown in `README.md`. Also reproducable by running `build.sh` in a Debian Sid VM.

Edit: Issue possible caused by missing `xserver-xorg-hwe-20.04` file in Ubuntu's repositories. See [this thread](https://forum.kde.org/viewtopic.php?f=309&t=169050) on KDE Neon forum.

**Comment by davidmhewitt** [comment]
There aren't any HWE packages for Ubuntu 20.04 yet. Disable HWE in your terraform config.
