### ISSUE TITLE
Installer crash when no HDD/SSD is found (5.1 Hera) 

### ISSUE THREAD

**Issue by etkaar** [elementary/os#421]
If I click on the add symbol in the partitioning process and no HDD/SSD is found, the installer will crash:

```
Traceback (most recent call last):
  File "/usr/lib/ubiquity/plugins/ubi-partman.py", line 1298, in on_partition_list_new_activate
    self.partman_dialog(devpart, partition)
  File "/usr/lib/ubiquity/ubiquity/plugin.py", line 48, in wrapper
    return target(self, *args, **kwargs)
  File "/usr/lib/ubiquity/plugins/ubi-partman.py", line 961, in partman_dialog
    if create and partition['parted']['type'] == 'pri/log':
TypeError: 'NoneType' object is not subscriptable

```

Parameters:
ISO on USB, UEFI mode

Screenshot:
https://i.ibb.co/THvkz8T/Screenshot-from-2020-12-13-06-46-53.png

**Comment by ijiki16** [comment]
Does ssd shows in windows Installer?
If yes, format ssd from there and then try elementary installer.

**Comment by pongloongyeat** [comment]
I'm not sure if you can expect this to be fixed since eOS6 now uses distinst instead of ubiquity.

**Comment by davidmhewitt** [comment]
elementary OS 5.1 uses the Ubuntu installer, Ubiquity, so a bug would need to be reported there. We do not maintain the Ubiquity installer.
