### ISSUE TITLE
Flatpak parental controls blocking Epiphany installation, making builds fail

### ISSUE THREAD

**Issue by kp2401075** [elementary/os#422]
While building elementary for AMD64 using elementary/os repo
```
Installing 7/7?                                                                    
Installing 7/7?                        0%  0 bytes/s
Installing 7/7? ?????                 21%
Installing 7/7? ?????                 22%
Installing 7/7? ?????                 22%  646.7?kB/s
Installing 7/7? ?????                 24%  704.6?kB/s
Installing 7/7? ??????                26%  821.0?kB/s
Installing 7/7? ???????               31%  526.4?kB/s
Installing 7/7? ?????????             42%  758.0?kB/s
Installing 7/7? ?????????????         63%  1.2?MB/s
Installing 7/7? ??????????????        67%  866.1?kB/s
Installing 7/7? ????????????????????  99%  800.1?kB/s  00:00
Error: Could not connect: No such file or directory                                  
error: Failed to install org.gnome.Epiphany: Could not connect: No such file or directory
E: config/hooks/live/001-install-flatpaks.chroot failed (exit non-zero). You should check for errors.
P: Begin unmounting filesystems...
P: Saving caches...
```
Not sure if this issue is already pickedup.

**Comment by tintou** [comment]
I think that it is related to https://github.com/flatpak/flatpak/pull/4022

**Comment by davidmhewitt** [comment]
Flatpak PR is now merged.

I've created the `flatpak-focal-patched` branch with the commit: https://github.com/elementary/os-patches/tree/flatpak-focal-patched

@danrabbit or @tintou , are you able to adjust the daily recipe to merge in that branch. I'm assuming it just builds directly off the `flatpak-focal` branch for now, as the `-patched` one didn't exist..

**Comment by danrabbit** [comment]
Recipe updated: https://code.launchpad.net/~elementary-os/+recipe/flatpak-focal

Running import...

**Comment by danrabbit** [comment]
@davidmhewitt alright looks like it built successfully in LP for amd64

**Comment by kp2401075** [comment]
I can confirm that this issues is resolved.

Thanks for the awesome work @davidmhewitt @tintou @danrabbit and all other elementary contributors. :smile:
