### ISSUE TITLE
Add MacOS support in docker build script [ Feature Request ]

### ISSUE THREAD

**Issue by ijiki16** [elementary/os#431]
# It would be nice to add support macOS to build elementary OS. 

I get this error when I'm trying to build:

```
#------------------#
# LIVE-BUILD BUILD #
#------------------#

[2021-01-07 19:09:16] lb build 
P: live-build 1:20190311
P: Building config tree for a ubuntu/bionic/amd64 system
[2021-01-07 19:09:17] lb bootstrap 
P: Setting up cleanup function
[2021-01-07 19:09:17] lb bootstrap_cache restore
[2021-01-07 19:09:17] lb bootstrap_debootstrap 
P: Begin bootstrapping system...
P: If the following stage fails, the most likely cause of the problem is with your mirror configuration or a caching proxy.
P: Running debootstrap... 
mknod: /working_dir/tmp/amd64/chroot/test-dev-null: Operation not permitted
E: Cannot install into target '/working_dir/tmp/amd64/chroot' mounted with noexec or nodev
P: Begin unmounting filesystems...
P: Saving caches...
```

Docker can't mount tmp folder from MacOS.

It would be nice if someone added support for macOS or help me to fix this error.

## My System

- OS: macOS Catalina 10.15.7 19H114 x86_64 
- Host: iMac13,2
- Kernel: Darwin 19.6.0
- CPU: Intel i5-3470S
- Memory: 16.00GiB

## Program

- Docker Desktop: 3.0.4 (51218)

**Comment by ibnesayeed** [comment]
I think this is a [known limitation of Docker for Mac](https://github.com/docker/for-mac/issues/291) and I found [someone else facing similar issues](https://forums.docker.com/t/docker-run-on-mac-with-mknod-support-on-volume-fuse-osxfs/60426). You can perhaps add a custom Dockerfile in this repo and build it, then copy the artifacts out from that image. This way, you can avoid volume mounting.

**Comment by davidmhewitt** [comment]
These build scripts are provided as-is and are used to build the released .iso images found on the website and at https://builds.elementary.io .

They are working fine for this purpose, so we have no intention to change them to work around docker limitations on other platforms.

If someone wanted to contribute some changes that fixed this without breaking the rest of the workflow or adding too much complexity, I don't think we'd object. But for now, I'll close this issue as there's no intention to do anything about it.

**Comment by AwlsomeAlex** [comment]
Hi! The issue you were running into was because of a limitation between the macOS APFS filesystem and Linux (Case sensitiveness). Its pretty easy to workaround by moving your working_dir into a Docker volume, then running the command with that new volume attached. I'm exploring this more on a branch along with two other issues macOS Docker carries. 

One of them has to do with networking timeouts when Docker is in bridged mode, and another is general RW speeds when Docker uses Hypervisor.framework instead of Virtualization.framework. 

It doesn't require any workflow changes, just alternative commands the user can run. I have it working with ARM64 builds, but need to get my hands on an x86 Mac to see if it carries the same issues.

**Comment by yozachar** [comment]
### Rootless podman build

[`etc/auto/config`](https://github.com/elementary/os/blob/fc6b6e1cbea922f02c139d157c11ce5902a87319/etc/auto/config#L28)

```diff
-    --debootstrap-options="--extractor=ar --keyring=/etc/apt/trusted.gpg" \
+    --debootstrap-options="--variant=fakechroot --extractor=ar --keyring=/etc/apt/trusted.gpg" \
```

[`build.sh`](https://github.com/elementary/os/blob/fc6b6e1cbea922f02c139d157c11ce5902a87319/build.sh#L27)

```diff
- apt-get install -y live-build patch gnupg2 binutils zstd
+ apt-get install -y live-build patch gnupg2 binutils zstd fakeroot fakechroot libpcre3 libsystemd-shared

...

-   lb build
+   fakechroot fakeroot lb build
```

`compose.yaml`

```yaml
name: elementaryos

services:
  iso:
    container_name: horus
    image: debian:latest
    volumes:
      - work_dir:/work_dir
      - /proc:/proc
    working_dir: /work_dir
    command: ./build.sh etc/terraform.conf

volumes:
  work_dir:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
```

`Build`

```console
$ podman-compose -f compose.yaml up
```
