### ISSUE TITLE
elementary OS 6.0 demo session does not have admin permissions

### ISSUE THREAD

**Issue by Akryum** [elementary/os#444]
Images on https://builds.elementary.io/downloads have a root password set (I don't know which one it is yet), which prevents from doing things from the live session such as launching "Install elementary OS":

![image](https://user-images.githubusercontent.com/2798204/107594872-659e8c80-6c13-11eb-80f7-961b28941a53.png)

**Comment by gamerlv** [comment]
There is no password set for either root or the 'elementary' user. This is also part of the problem you're encountering, the demo mode user is not allowed to modify the live environment so needs to asks for additional privileges. Polkit however is not allowed to accept a blank password, which the 'elementary' user has.

It is possible to continue installing a early access build by logging out of demo mode using the system menu in the top right. This will bring you back to the installer.

(Checked on build 6.0-daily.20210210)

**Comment by Akryum** [comment]
Problem is, when I'm not in a live session, the installer is unusable at 800x600:

![image](https://user-images.githubusercontent.com/2798204/107620176-9a7f0380-6c54-11eb-8c35-272d57a2517a.png)

**Comment by Akryum** [comment]
(I'm using Virtualbox 6.1.16)

**Comment by Akryum** [comment]
I think I have a better version when enabling EFI
![image](https://user-images.githubusercontent.com/2798204/107620582-37da3780-6c55-11eb-870c-3364845dc174.png)

**Comment by okitoxo** [comment]
That problem happening when I want do an Custom Install and open Gparted from Demo Mode.

**Comment by ibnesayeed** [comment]
https://github.com/elementary/installer/pull/486 might solve this issue (I have reported a similar issue https://github.com/elementary/installer/issues/468 earlier).

For now, you can open the terminal and run `su elementary` command then set a password (this is described in https://github.com/elementary/switchboard-plug-sound/issues/181).

**Comment by davidmhewitt** [comment]
This should have been resolved by https://github.com/elementary/installer/pull/486
