### ISSUE TITLE
Include HWE kernel in 6.0 builds

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#445]
It looks like we're not shipping the HWE kernel yet, but Ubuntu 20.04.2 has been released with 5.8 which would be good to get, especially for AMD machines and OEMs.

**Comment by davidmhewitt** [comment]
Just as a quick note to save someone some time if they pick this up before me. It's not quite as simple as setting HWE to yes in the config this time as that causes our scripts to try adding a matching HWE version of Xorg too, which doesn't seem to exist in the Ubuntu repos this time around. So there will be a minor bit of refactoring to split that out.

**Comment by davidmhewitt** [comment]
Also, as another note, installing the HWE kernel on an already running 6.0 build with `sudo apt install linux-generic-hwe-20.04` probably won't trigger the necessary GRUB updates to actually boot into it. We need to patch GRUB before that will happen automatically as detailed here: https://github.com/elementary/os-patches/issues/91#issuecomment-777483935

As a workaround if you want to try the HWE kernel, run `sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub/grub.cfg` after installing the kernel to force the GRUB config update.

**Comment by cassidyjames** [comment]
@davidmhewitt I just ran `sudo apt-get install --install-recommends linux-generic-hwe-20.04` on my Star LabTop and rebooted, and am now running 5.8—but I don't believe this machine has Secure Boot enabled, if that makes a difference? It's definitely something we can test more.

**Comment by davidmhewitt** [comment]
Hm, I guess secure boot could be a factor. I did the same thing on my Dell XPS today and didn't get the new kernel until I ran `grub-mkconfig`.

What's the output of `sudo efibootmgr --verbose` ?
