### ISSUE TITLE
HP  14m-dw1013dx (x360) Touchpad/Touchscreen are not Functioning. 

### ISSUE THREAD

**Issue by BluePr1nt-X** [elementary/os#451]
[Driver-Touchpad_output.txt](https://github.com/elementary/os/files/6071255/Driver-Touchpad_output.txt)

This appears to be a bug and has been address in a future kernel, however to keep stability of Hera, I have declined to stick with the mainline 5.11 kernel.  This seems to affect many users on ubuntu as well. How soon can the team implement a patch for this issue?  Thanks! 

Link: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1853277 

Link: ( AMD work around) - https://bugzilla.kernel.org/show_bug.cgi?id=207759#c17

**Comment by davidmhewitt** [comment]
elementary ships an unmodified Ubuntu HWE kernel, we don't apply an specific patches for specific hardware. If this is still an issue, you would need to follow this up on the Ubuntu bug tracker.
