### ISSUE TITLE
/boot/efi/EFI/ubuntu/grub/grub.cfg not updating after installing another kernel

### ISSUE THREAD

**Issue by bailtree** [elementary/os#456]
I installed the xanmod kernel but only the default kernel is shown in the grub menu after a reboot.
Running update-grub doesn't make a difference.

Looking at /boot/grub/grub.cfg, that has been updated, and I can see a xanmod kernel entry in there.

I have tried this on a VM and on the host itself.

/boot/efi/EFI/ubuntu/grub/grub.cfg is attached
[grub.zip](https://github.com/elementary/os/files/6215275/grub.zip)

My workaround: copy /boot/grub/grub.cfg to /boot/efi/EFI/ubuntu/grub/ and overwrite the existing grub.cfg

**Comment by linuxkettle** [comment]
You should have a small grub.cfg file of about 3 lines in your EFI partition, that loads the one in your boot folder. Like for me,
```
# cat /boot/efi/EFI/ubuntu/grub.cfg
search.fs_uuid 8e2a9073-72b3-4cba-bf15-3704b810f72a root hd0,gpt7 
set prefix=($root)'/boot/grub'
configfile $prefix/grub.cfg
```

**Comment by bailtree** [comment]
```
# cat /boot/efi/EFI/ubuntu/grub.cfg
search.fs_uuid 44FB-ACAE root hd0,gpt1 
set prefix=($root)'/EFI/ubuntu/grub'
configfile $prefix/grub.cfg
```

**Comment by linuxkettle** [comment]
That is very strange. The point of having a file stub like that is to put the main config file on your Linux partition, instead of just a different location on the ESP, which is usually very small and you want to put as little as possible on it.

Can you run `cat /boot/efi/EFI/ubuntu/grub/grub.cfg`?

**Comment by bailtree** [comment]
I attached that file to the original post, in a zip file.

**Comment by linuxkettle** [comment]
What's your root partition (the one with elementary on it, e.g. /dev/sda7 for me)

**Comment by davidmhewitt** [comment]
@bailtree Please state what version of elementary OS you are running in issue reports.

If this is the daily 6.0 images. This issue will occur because we haven't patched Ubuntu's version of GRUB yet. You can run `sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub/grub.cfg` after installing a kernel to manually refresh the config.

**Comment by linuxkettle** [comment]
If you're not sure, run `mount | grep "on / type"` and the first column is your root partition.

**Comment by bailtree** [comment]
Thanks both. I'm sorry that I didn't state the version. I am using the daily 6.0 images.

**Comment by cassidyjames** [comment]
For reference, https://github.com/elementary/os-patches/issues/168 is the related issue

**Comment by KarkanAlzwayed** [comment]
@davidmhewitt  

> after installing a kernel to manually refresh the config.
I don't get this part. I have run that command and I am still getting that blue screen. I know I am doing something wrong.

**Comment by Rantyrant** [comment]
@KarkanAlzwayed What do you mean?
The command just makes sure the newest installed kernel is actually shown in Grub.
I assume the "blue screen" is just the default colour config for Grub because they haven't loaded in an image to use just yet.

**Comment by KarkanAlzwayed** [comment]
@Rantyrant the issue isn't having a blue or a green screen, the issue is that there is a grub screen showing up with a wait time of 20 seconds even though the grub timeout is set to zero in /etc/default/grub

**Comment by Rantyrant** [comment]
@KarkanAlzwayed Yep, that's because the config doesn't actually seem to source the changes made in /etc/default/grub. I actually don't really know where it sources them from. Again, I would assume they're aware, seeing that's why they want to patch, and also why it doesn't update with new kernels.
