### ISSUE TITLE
The Flatpak repo has disappeared

### ISSUE THREAD

**Issue by pnfcre** [elementary/os#473]
Hi there,

It looks like the Flatpak repo [has disappeared](https://flatpak.elementary.io/elementary.flatpakrepo), causing builds to [break](https://github.com/elementary/os/runs/2443556909?check_suite_focus=true). Changing the URL in [`etc/config/hooks/live/001-install-flatpaks.chroot`](https://github.com/elementary/os/blob/master/etc/config/hooks/live/001-install-flatpaks.chroot#L6) to `https://flatpak.elementary.io/repo.flatpakrepo` results in another build error:

```
Looking for matches?
error: Nothing matches io.elementary.calculator in remote elementary
Looking for matches?
error: Nothing matches org.gnome.Epiphany in remote elementary
 config/hooks/live/001-install-flatpaks.chroot failed (exit non-zero). You should check for errors.
E:P: Begin unmounting filesystems...
P: Saving caches...
```

Kind regards,
Hampus Kraft.

**Comment by btkostner** [comment]
Yes. Sorry about that. We determined that it was better to have a single repository instead of two separate ones for elementary and AppCenter. We are in the process of rebuilding the repo now

**Comment by cassidyjames** [comment]
Closing since this is being resolved, and there's nothing to do in the OS repo for it.

**Comment by rsilvestre** [comment]
@cassidyjames Hi, is it fixed, because I still have the issue ?

**Comment by cassidyjames** [comment]
@rsilvestre you should be able to look at https://github.com/elementary/os/blob/master/etc/config/hooks/live/001-install-flatpaks.chroot and update your Flatpak repos to match that.
