### ISSUE TITLE
Evaluate shipped fonts

### ISSUE THREAD

**Issue by codygarver** [elementary/os#49]
There's a ton in Juno now, do we need them all? See [attached list](https://github.com/elementary/os/files/1707330/fonts.txt).

**Comment by grvrulz** [comment]
Since you're shipping the Noto fonts, all Lohit-* and a few other Indic fonts can be dropped IIRC. I'll take a deeper look at which Indic languages are supported by the shipped Noto, and will leave some notes here tomorrow.

**Comment by grvrulz** [comment]
With Noto fonts installed, you shouldn't need these ones(and their dependencies) at least:

- fonts-gujr	2:1.2  
- fonts-gujr-extra	1.0-6  
- fonts-guru	2:1.2  
- fonts-guru-extra	2.0-4  
- fonts-indic	2:1.2  
- fonts-lohit-beng-assamese	2.91.5-1
- fonts-lohit-beng-bengali	2.91.5-1
- fonts-lohit-deva	2.95.4-2
- fonts-lohit-gujr	2.92.4-2
- fonts-lohit-guru	2.91.2-1
- fonts-lohit-knda	2.5.4-1
- fonts-lohit-mlym	2.92.2-1
- fonts-lohit-orya	2.91.2-1
- fonts-lohit-taml	2.91.3-1
- fonts-lohit-taml-classical	2.5.4-1
- fonts-lohit-telu	2.5.5-1
- fonts-mlym	2:1.2
- fonts-orya	2:1.2
- fonts-orya-extra	2.0-5
- fonts-taml	2:1.3
- fonts-telu	2:1.2
- fonts-telu-extra	2.0-4

**Comment by codygarver** [comment]
@grvrulz thanks, this helped a lot. It turns out these are all dependencies of `fonts-indic` so I tracked down that dependency and removed it.

I will make a follow up comment about what other specific fonts I'm curious about.

**Comment by codygarver** [comment]
These are some specific font packages I am curious about the usefulness of now:

* fonts-dejavu-core
* fonts-freefont-ttf
* fonts-kacst-one
* fonts-khmeros-core
* fonts-lao
* fonts-liberation
* fonts-lklug-sinhala
* fonts-sil-abyssinica
* fonts-sil-padauk
* fonts-thai-tlwg
* fonts-tibetan-machine

**Comment by grvrulz** [comment]
I think `fonts-lklug-sinhala` should also be deprecated by Noto.

`fonts-freefont-ttf` and `fonts-liberation` are probably shipped sor Microsoft font compatibilityl. IMHO the criscore and crosextra font packages for that.

We probably need more input on the rest of them.

**Comment by codygarver** [comment]
# Font update for 2018-07-11

Removed as superseded by **Croscore**:
* fonts-freefont-ttf
* fonts-liberation

Removed as superseded by **Noto**:
* fonts-khmeros-core
* fonts-lao
* fonts-lklug-sinhala
* fonts-thai-tlwg
* fonts-tibetan-machine
* fonts-tlwg-garuda
* fonts-tlwg-kinnari
* fonts-tlwg-laksaman
* fonts-tlwg-loma
* fonts-tlwg-mono
* fonts-tlwg-norasi
* fonts-tlwg-purisa
* fonts-tlwg-sawasdee
* fonts-tlwg-typewriter
* fonts-tlwg-typist
* fonts-tlwg-typo
* fonts-tlwg-umpush
* fonts-tlwg-waree

Remaining that I'm unsure about:
* fonts-arphic-ukai
* fonts-arphic-uming
* fonts-dejavu-core
* fonts-kacst
* fonts-kacst-one
* fonts-nanum-coding
* fonts-sil-abyssinica
* fonts-sil-mondulkiri
* fonts-sil-padauk
* fonts-unfonts-core
* gsfonts

**Comment by codygarver** [comment]
Unless I learn anything new about the remaining fonts soon, I'm probably gonna consider this issue addressed and close this ticket.
