### ISSUE TITLE
`org.freedesktop.Platform.GL.default` still not pre-installed in ISOs

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#492]
We include a filtered Flathub now, but the GL extension is not being automatically pulled in when we install Epiphany; I'm not sure if there's something else we need to do when installing Epiphany, or if we should just manually install the extension as well, e.g. with:

```
flatpak install --system freedesktop org.freedesktop.Platform.GL.default//20.08
```

**Comment by Marukesu** [comment]
it should to be auto-installed with the Platform. That's what happens with the gnome and fdo platforms on flathub, maybe because it on a different repository it don't get installed with it?

**Comment by cassidyjames** [comment]
@Marukesu yeah that's what I'm guessing... but that's also concerning re: NVIDIA extension, if they won't get automatically installed when running a Flatpak update.
