### ISSUE TITLE
Include option for FacetimeHD Drivers // Drivers not working in Odin RC3

### ISSUE THREAD

**Issue by supaeasy** [elementary/os#522]
Would be great if somehow Camera Drivers for (older) MacBooks worked out of the box. Also had some problems with proprietary drivers (WiFi) in general, as I found no Option yet to include them during installation (guess it comes with the final Version) but was able to fix it eventually. With Hera I got the Camera running but with Odin RC3 I am having Problems.

Maybe steps from here could be somehow included in the distro/AppCenter?
https://github.com/patjak/bcwc_pcie/wiki/Installation#get-started-on-ubuntu

Getting these errors in RC3: 
```
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
```

**Comment by aharish** [comment]
Yep, can again confirm that I have the same errors, but on the latest stable install on a MacBook Air 6,1.

I did read [here](https://victorleungtw.com/2020/04/24/install-ubuntu-20-04-lts-on-macbookpro141/) of an alternate way to install the driver when encountering the SSL error (which is actually an issue with Ubuntu, and not with elementary itself), but that failed to work for me.

**Comment by davidmhewitt** [comment]
elementary ships with unmodified Ubuntu kernels.

Any proposals for additional drivers to be included in the kernel would have to be submitted to Ubuntu.
