### ISSUE TITLE
Odin 6: Black screen when login from lockscreen

### ISSUE THREAD

**Issue by tienhuynh5312** [elementary/os#528]
Hi,

I am currently using Odin 6 on my thinkpad t480 (i5 8250u).

Reproduce the issue:
1. Initiate lock screen by menu or shortcut Windows+L

2. The computer display goes black and move mouse or press keyboard to turn on the display.
3. Login again.
4. Blank screen with only mouse cursor visible

Thank you.

**Comment by ImranR98** [comment]
Also happens on a Lenovo Yoga 720. Can't reproduce it reliably, though. It doesn't happen right after locking, but does after the lid has been closed for a while.

**Comment by ryonakano** [comment]
Closing as a duplicate of elementary/gala#1126
