### ISSUE TITLE
In-Place update from Elementary OS 5.1.7 to Elementary 6 MISSING

### ISSUE THREAD

**Issue by AnimishY** [elementary/os#538]
The issue in short: Missing option for In-Place Update from Hera to Odin.

![image](https://user-images.githubusercontent.com/66960835/129583618-5d7871b7-f867-4bcd-a445-6bebbaa7a85c.png)

Thought the options is available, it is not showing anything

### Discussed in https://github.com/elementary/os/discussions/535

<div type='discussions-op-text'>

<sup>Originally posted by **AnimishY** August 15, 2021</sup>
I have a device of configuration: i3, 4GB RAM, 1TB HDD, Dual Booted to Windows 10 and Elementary 5.1.7 with 125 GB for Elementary OS.

The sole reason to have Dual Boot on such weak and old device was that it was becoming difficult for the device to handle Windows 10 with a web-browser and a video conferencing app together and work without hanging for hours. So to ease my day to day work, I switched to Elementary OS, with no knowledge of Linux at all. I just knew how to make an ISO file to boot able media and install it. 

So I have been using it for months, and now I wish to update to Elementary OS 6, so my basic question is **_how to update to V6 from V5.1.7 without opting for a fresh/clean start, losing all apps and data._** I checked the official website it says nothing for those who already are on the OS, and in the System Settings app, it shows no components is available to update.

Please note I am a 15 year old student with least knowledge of Linux, so please explain all steps, all commands you may refer to. I know it may be a lot extra effort to explain in such manner, and it would really nice of all of you guys to help me out.

Thanks & Regards,
Animish Yadav</div>

**Comment by cassidyjames** [comment]
@AnimishY thanks for filing this! We do have the FAQ on the homepage, in the blog post, and on social media which addresses this as the first question. For tracking the issue on GitHub, we have this issue: https://github.com/elementary/triage/issues/46
