### ISSUE TITLE
sudo nano /etc/apt/sources.list

### ISSUE THREAD

**Issue by beniardiyanto** [elementary/os#539]
how to manage sudo nano /etc/apt/sources.list ?

NAME="elementary OS"
VERSION="6 Odin"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6 Odin"
LOGO=distributor-logo
VERSION_ID="6"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=odin
UBUNTU_CODENAME=focal

**Comment by cassidyjames** [comment]
@beniardiyanto I'm not sure what you're asking exactly or trying to accomplish. Could you clarify what you’re trying to do exactly?
