### ISSUE TITLE
Odin install failed: archive extraction failed

### ISSUE THREAD

**Issue by AI-ien** [elementary/os#547]
I don't understand where is my mistake, maybe someone can enlighten me. I'm using latest ISO `elementaryos-6.0-stable.20210823.iso`, SHA256 is correct, tried with three different USB keys, the same result that ends with error.

I'm using following steps:
1. disable Secure boot in BIOS
2. Launch USB ISO eOS install
3. pass all package checks
4. choose languages
5. choose manual partition selection
6. choose partitions: EFI partition `boot/EFI` (466Mb FAT32), btw, had to resize because 100Mb was too small and root `/` that is previous Hera 5.1 install. Thats it.
7. Press `Erase all and install` that after about 15% progress results on fail

Btw I use dual boot with Windows 10. That button `Erase all and install` is very confusing. What is install script really doing? Does it format selected partitions? If so, it is very alarming for dual boot systems, because I don't want it to format EFI or HOME partitions.

![20210828_162648](https://user-images.githubusercontent.com/33252703/131229196-4b7680aa-91b0-44fb-8b7b-85ece674aaf8.jpg)

Odin install error log
```bash
---
INFO: mounting temporary chroot directory at distinst 
INFO: mounting all targets to the temporary chroot
INFO: mounting /dev/nvme@n1p7" (ext4) to "/tmp/-distinst.hiVgFeqC7qMQ/"
INFO: mounting /dev/nvmeOn1p2" (vlat) to "/tmp/-distinst.hiVgFeqC7qMQ/boot/efi"
INFO: starting extracting step
INFO: Extracting /cdrom/casper/filesystem.squashfs
DEBUG: "unsquashfs" "-f" "-d" "/tmp/-distinst.h1VgFeqC7qMQ" "/cdrom/casper/-
filesystem.squashfs"
ERROR: extracting error: archive extraction failed with status: exit code: 1
```

**Comment by davidmhewitt** [comment]
How big is the / (root) partition you're trying to install to?

**Comment by AI-ien** [comment]
> How big is the / (root) partition you're trying to install to?

23Gb

**Comment by davidmhewitt** [comment]
Hm, it's a little on the small side, but that should be big enough, but I have seen that error before when the root partition is too small. Have you told the installer to format the partition first? Maybe try giving a bit more space if you can.

Do the checksums while the iso is booting pass?

What language are you installing in? There are some other issue reports about failing to install in certain languages, but I think it's a different error.

**Comment by AI-ien** [comment]
All checksums passed and all languages are default, but I feel silly. When selecting partitions there is a drop-down with option to format. Somehow my brain didn't glue with it so installator tried to extract package on already full partition and fails. 

Formating partition before install or toggling that button solved the issue. Sry for caused trouble for nothing. All now works, case can be closed.

**Comment by davidmhewitt** [comment]
Thanks for the update, glad you got the issue resolved!

**Comment by gitoso** [comment]
Greetings,

I've been having the same problem and I just can't figure out what's happening. The steps I am following are exactly the same, but I am indeed checking the format option.

Already tried to redownload the image (and confirmed the checksum), tried with more than one different USB sticks and nothing seems to work.

Tried changing the language and partition sizes are:
- 1GB EFI Partition (FAT32)
- 84GB / (ext4)

We scanned the partition for badblocks and no one was detected.

Any ideas?

**Comment by gitoso** [comment]
SOLVED

In our case, balenaEtcher was the problem. We used it on two different systems and the installation media was not working. Tried with other alternatives afterwards and installation worked flawlessly. Not sure why this happened, but I confirm that is has nothing to do with the image file.
