### ISSUE TITLE
Why not switch to Pipewire?

### ISSUE THREAD

**Issue by subnut** [elementary/os#575]
### Problem

Pulseaudio has very noticeably latency issues

### Proposal

Switch to Pipewire, which doesn't have latency issues

**Comment by cassidyjames** [comment]
Note there is also an open discussion at https://github.com/elementary/os/discussions/552

**Comment by danyildiabin** [comment]
I support decision of switching to pipewire because few devices I own have issues when plugging and unplugging 3.5 mini-jack on Pulseaudio. Automatic source switching doesn't work well or works with bad delays on Pulseaudio. Pipewire works well out of the box on other distros I used.

**Comment by Ppamungkas** [comment]
Tried the pipewire on 7.x, everything looks good, should be a default.

**Comment by danirabbit** [comment]
I can confirm that we're running pipewire in the latest OS 8 daily :tada:
