### ISSUE TITLE
Request: a doc that points people to the right place to ask a question

### ISSUE THREAD

**Issue by SephReed** [elementary/os#616]
The "Report an issue with Elementary OS" button leads to 140 repositories and no direction.  If that link could instead go to a doc that gives a bit of direction, that would really help a ton.

![Screenshot from 2022-03-17 15-49-23](https://user-images.githubusercontent.com/14002040/158900489-5d766c20-0a97-4c5d-be1a-270a788dfe2e.png)

**Comment by tintou** [comment]
It already exists within the system, open the System Settings and go to the System section, then you have a `Send feedback` button
![Capture d'écran du 2022-03-18 08 37 32@2x](https://user-images.githubusercontent.com/745535/158957326-3bc21d6c-43bb-41b3-8616-dc796d6c766b.png)
this leads you to a step-by-step process
![Capture d'écran du 2022-03-18 08 37 49@2x](https://user-images.githubusercontent.com/745535/158957487-bb4d187b-7462-4cfb-8c6c-fd9b7d839f25.png)
and it then redirects you to the right repository

**Comment by SephReed** [comment]
This is cool.  You guys should replace the super unhelpful "Report an issue with Elementary OS"  button with directions towards this answer.

**Comment by danrabbit** [comment]
@SephReed can you elaborate on where you're seeing this button?

**Comment by SephReed** [comment]
Here's the flow I've ended up in a few times:

- Search Google (featured top hit is lame, sorry about that): https://www.google.com/search?q=elementary+os+issues
![Screenshot from 2022-05-23 13-37-57](https://user-images.githubusercontent.com/14002040/169893880-8b4eebde-4b03-4210-ae9d-9a97264a12c4.png)


- Go to top non-featured hit (Issues for EOS): https://github.com/elementary/os/issues
![Screenshot from 2022-05-23 13-38-05](https://user-images.githubusercontent.com/14002040/169893918-1080cb16-07d1-44e1-b5b2-df499ebd47f1.png)

- New Issue: https://github.com/elementary/os/issues/new/choose
![Screenshot from 2022-05-23 13-38-45](https://user-images.githubusercontent.com/14002040/169893965-36e8fffd-123b-4dbd-9f84-9cb6c6645dd0.png)

- Follow the third link.  Not really any directions from here: https://github.com/elementary
![Screenshot from 2022-05-23 13-39-01](https://user-images.githubusercontent.com/14002040/169894090-7c6845d4-de3d-4610-8702-aa3a140999b6.png)

**Comment by danrabbit** [comment]
Ah sorry, not sure how I missed that from your original report. I've created #619 to point to our contributor guide instead of dumping you in our github org
