### ISSUE TITLE
i am not understanding how to modify your source code and compile it i want to do it offline please help and provide documentation

### ISSUE THREAD

**Issue by leafway** [elementary/os#620]

**Comment by alinourzad** [comment]
everything is documented pretty well.

**Comment by ZenitsuDev** [comment]
do you have a specific application you need to compile? Compilation and installation instructions are in every app readme. If you want to use the desktop, there are ppa's for ubuntu, aur for arch but of course the best experience with the apps will be in elementary os itself 😊

**Comment by davidmhewitt** [comment]
Closing due to no response or clarification from OP.
