### ISSUE TITLE
Kernel panics when trying to boot ISO on T2 Macs.

### ISSUE THREAD

**Issue by AdityaGarg8** [elementary/os#644]
When we try to boot the ISO on T2 Macs, the kernel panics and the Mac suddenly powers off with fans running at full speed.

This was an issue which was fixed in this commit upstream :- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/nvme?h=v6.2-rc1&id=a2941f6aa71a72be2c82c0a168523a492d093530

However the kernel used by elementary OS doesn’t have this fix incorporated and thus the panic occurs.

A fix should be patching the kernel with this patch already upstreamed.

**Comment by meisenzahl** [comment]
Closing because we use the Ubuntu hardware enablement stack, so any requests for hardware support should be implemented upstream in Ubuntu.
