### ISSUE TITLE
Build using wrong branch names

### ISSUE THREAD

**Issue by Sean-StarLabs** [elementary/os#646]
The build script seems to use the values from `lsb-release` and these don't match the branch names in other repositories

i.e. It tries to clone branch `jolnir` from https://github.com/elementary/seeds which doesn't exist

**Comment by tintou** [comment]
Thanks for catching it, we've had one last minute change with lsb-release, it should be sorted with https://github.com/elementary/os/commit/ca27d3aadd536d0abaf588f4433df6ef07a4500c

**Comment by Sean-StarLabs** [comment]
That does the trick, thanks :)
