### ISSUE TITLE
please help how to install on ARM processor

### ISSUE THREAD

**Issue by an-elementary-os-user** [elementary/os#647]
i want install on arm. i not want pay to elementary. please help install on arm. please not close as i not know what right repsoritory is. please helpe

**Comment by davidmhewitt** [comment]
The only ARM devices supported are the Raspberry Pi 4 and the Pinebook Pro. These are not considered stable, and therefore built images are only available through the early access program.

If you wish to build images for these devices yourself, you can do so with the scripts and instructions in this repository.

**Comment by aitor-gomila** [comment]
As a sidenote, Elementary OS is free. The paid options are optional, but they help development ;) I can't pay right now because I don't have a credit card, but I will as soon as I can.
