### ISSUE TITLE
terraform.conf is out of date

### ISSUE THREAD

**Issue by peteruithoven** [elementary/os#655]
I've cloned this repo and build it following the [64-bit AMD/Intel](https://github.com/elementary/os#64-bit-amdintel) instructions, but it seems to generate an iso with 6.0 in the name, instead of 7, what I would expect at this moment.  
Full filename: `elementaryos-6.0-stable.20230215.iso`.

**Comment by peteruithoven** [comment]
Booting into it, the installer also mentions 6.1. So I might be doing something wrong. 
![IMG_20230215_135519-2000](https://user-images.githubusercontent.com/523210/219049740-64584d21-0b06-4a20-b7ee-cba293e8bf6c.jpg)

**Comment by peteruithoven** [comment]
Ah, to use the stable 7.0 release I needed to use the `terraform-stable-azure.conf`. So:
```
docker run --privileged -i -v /proc:/proc \
    -v ${PWD}:/working_dir \
    -w /working_dir \
    debian:latest \
    /bin/bash -s etc/terraform-stable-azure.conf < build.sh
```

In `/etc/config`, in the `.conf` files see the `VERSION`.

**Comment by davidmhewitt** [comment]
Indeed, the default `terraform.conf` needs updating to match `terraform-stable-azure`, but not using the azure mirrors. Feel free to open a PR 😉 

The ones with azure mirrors are used for building in GitHub actions, but work fine for regular use too.

**Comment by peteruithoven** [comment]
I'm happy to, but I'm a bit confused. You say `terraform.conf` should not use azure mirrors? But all the terraform configurations seem to use the same Azure mirror (`http://azure.archive.ubuntu.com/ubuntu/`). I don't know what else to use.

**Comment by davidmhewitt** [comment]
> I'm happy to, but I'm a bit confused. You say `terraform.conf` should not use azure mirrors? But all the terraform configurations seem to use the same Azure mirror (`http://azure.archive.ubuntu.com/ubuntu/`). I don't know what else to use.

Hm, it looks like this has been inadvertently changed at some point. I think it's better to use `archive.ubuntu.com` instead of `azure.archive.ubuntu.com`.

I find that I get slow speeds when I use the azure mirror on my home connection. But azure is definitely the best mirror to use for the automated builds that GitHub Actions does, since GitHub Actions is hosted in azure.
