### ISSUE TITLE
elementaryOS 8.0 (daily) would not boot up properly. (Greeter problem, perhaps?)

### ISSUE THREAD

**Issue by darltrash** [elementary/os#710]
I have tried to build elementaryOS 8.0 (x86_64) myself using the build system provided by this repo (8.0-daily branch) but after booting it up, it would simply not show me any greeter and plymouth would start flashing slowly, fading in and out.

## My system:
- OS: Fedora Workstation 38 (x86_64)
- Docker: 24.0.5

## The steps I did:
```shell
git clone https://github.com/elementary/os
cd os
git checkout danirabbit/daily-8.0
git fetch
# git branch
docker run --rm --privileged -it -v /proc:/proc -v ${PWD}:/working_dir -w /working_dir debian:latest ./build.sh etc/terraform-daily-8.0-azure.conf
```
Then used Fedora Media Writer to write out the ISO onto an usb drive.

## My own research:
I went on and investigated the issue on my own, and apparently it seems to be a problem with the greeter OR some missing file within the live environment, I did not modify the script nor the ISO in any way.

Here are some useful files that I could gather from the logs:
[log/lightdm/lightdm.log](https://github.com/elementary/os/files/15045703/lightdm.log)
[log/lightdm/seat0-greeter.log](https://github.com/elementary/os/files/15045704/seat0-greeter.log)

It seems to lack a file at `/home/elementary/.face`? but weirdly enough, it says something along the lines of "Operation not permitted"?

## On another note..
The reason of why I decided to build this myself is because me and a friend have tried to join the Github Sponsors program and for some reason, it would not accept our debit cards. We are not from the US but we are in the list of "supported countries."

We also tried Patreon and it's the same problem...

Anyways, I am very hyped for this project, it is really my favourite linux distro (and OS!) out there ever since I joined the Linux/FOSS world about 6 years ago, literally the only reason of why I am on Fedora right now is because of Wayland and Pipewire. Thanks Danielle, Cassidy and the whole team for having made such a wonderful project! Best of luck to everyone!

**Comment by celiopy** [comment]
The last one that I was able to boot and install is `elementaryos-8.0-daily.20240328.iso`. Updating it post install also produces the same behavior after reboot.

**Comment by darltrash** [comment]
> The last one that I was able to boot and install is `elementaryos-8.0-daily.20240328.iso`. Updating it post install also produces the same behavior after reboot.

I was literally just about to mention that I finally got to sponsor elementaryOS, and that even though I tried the officially built ISOs, it didnt boot up.

Thanks for the info though! Very useful, will try later today.

**Comment by marqu3s** [comment]
I'm also a fan of Elementary OS since version 5. Now with a more confortable financial situation decided to sponsor the project.

Unfortunately the build from 2024-03-28 is not available anymore in the previous builds.

**Comment by BAProductions** [comment]
Does sponsoring EOS allow you to upgrade from EOS 6/7 to 8

**Comment by danirabbit** [comment]
@BAProductions please keep things on topic. No, we don't gate features behind a pay wall.

**Comment by danirabbit** [comment]
The latest daily is once again bootable. Thanks @davidmhewitt :)

**Comment by darltrash** [comment]
YAYYYY
