### ISSUE TITLE
`.iso` with cumulative updates for newbie

### ISSUE THREAD

**Issue by sauntor** [elementary/os#711]
### What Happened?

The iso image always stays in the day when it released, but updates after some months may be too large and waste time to update online 

### Steps to Reproduce

As *What Happend* says.

### Expected Behavior

Maybe, we can update the iso image with updates cumulate to last week/month/feature

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
I proposed and merged https://github.com/elementary/os/pull/704 to make sure we build a new ISO every month :)
