### ISSUE TITLE
Firefox window incompatible with the system

### ISSUE THREAD

**Issue by valex199132** [elementary/os#713]
Hello, I would like to report a bug that affects the stable version of Elementary OS (7.1) and also the current test version (8.0). Apparently the window size adjustment button is not compatible with Firefox. Instead of being on the right of the browser window, it is on the left, next to the close button. I haven't observed this behavior with any other app, only this one.

![Screenshot 2024-06-08 at 12-40-07 Screenshot from 2023-05-26 22 43 18 jpg (imagem JPEG 1366 × 768 pixels) - Redimensionada (85%)](https://github.com/elementary/os/assets/159088913/1571e299-e856-4765-bb76-ec85536ac9c9)

**Comment by danirabbit** [comment]
elementary doesn’t make or distribute Firefox. You’ll need to report Firefox issues to Mozilla: https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla
