### ISSUE TITLE
Deprecated PPA key algos

### ISSUE THREAD

**Issue by vjr** [elementary/os#714]
When doing a `sudo apt update` in the terminal you see the following:

```
W: https://ppa.launchpadcontent.net/elementary-os/daily/ubuntu/dists/noble/InRelease: Signature by key 6C8769CEDC20F5E66C3B7D37BF36996C4E1F8A59 uses weak algorithm (rsa1024)
W: https://ppa.launchpadcontent.net/elementary-os/os-patches/ubuntu/dists/noble/InRelease: Signature by key 6C8769CEDC20F5E66C3B7D37BF36996C4E1F8A59 uses weak algorithm (rsa1024)
```

Does this mean the PPA signing keys should be updated?

**Comment by davidmhewitt** [comment]
The noble PPA is already dual-signed with a newer algorithm as well as the older one, we just need to update the keys we inject into the image to use the rsa4096 key instead.

**Comment by vjr** [comment]
Thanks - I guess this is a bite size fix which I can attempt - so I'll open a (hopefully working) PR shortly.
