### ISSUE TITLE
arm64: Cleanup artifacts before build process

### ISSUE THREAD

**Issue by ryonakano** [elementary/os#730]
`build-rpi.sh` and `build-pinebookpro.sh` does not cleanup artifact directory from previous build, which causes debootstrap failed on second execution:

https://github.com/elementary/os/pull/728#issuecomment-2453594597

**Comment by stsdc** [comment]
There is that tool that allows to build raspberry os in stages. It means you don't need to remove the whole filesystem, if a change is small/in last stage of a creating an image. https://github.com/RPi-Distro/pi-gen

I understand that it is might not be applicable currently for elementary os. Leaving it here rather as interesting concept.

**Comment by ryonakano** [comment]
Yeah it is ideal if we can reuse stuff from previous build. However, it would require some (breaking) changes to our scripts to use pi-gen. I guess we may want to remove the whole artifacts for now and switch to pi-gen later if we want.

Would you create a new issue as a feature request with the above info, so that it won't buried in a closed issue?
