### ISSUE TITLE
Disable fwupd/LVFS phoning home

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#86]
[fwupd phones home](https://blogs.gnome.org/hughsie/2018/01/10/phoning-home-after-updating-firmware/) to LVFS with [a bunch of data](https://fwupd.org/privacy) when running. While we don't use GNOME Software (so I don't believe fwupd/lvfs stuff are automatically running), we should protect user data, especially when they've never opted to give any data to that third party.

According to the post, 
>You can disable the reporting functionality in all applications by editing /etc/fwupd/remotes.d/*.conf

We should do so in elementary OS.

**Comment by tintou** [comment]
It should be opt-out, if you look at the information that are sent, it's completely legitimate. It helps vendors knowing that a failure occured.
>  Machine ID (hashed), failure string and checksum of failing file, OS distribution name and version.

**Comment by cassidyjames** [comment]
Regardless of the data being collected, according to [the fwupd/LVFS own privacy policy](https://fwupd.org/privacy) they require **active consent**, meaning opt-in.

>The data that we collect is subject to active consent by the data subject. This consent can be revoked at any time. Revoking consent to use data ends any vendor relationship with the LVFS.

**Comment by N00byKing** [comment]
Why not make it an option during install...

**Comment by lewisgoddard** [comment]
@N00byKing I assume that with a new installer not slated for this release and at this stage in the release cycle, this won't be an option in the installer for this release. Maybe next time.

**Comment by danrabbit** [comment]
Yes, opting in to statistics should be a part of onboarding, but like Lewis said at this point in the cycle it won't make it in. So the safest thing to do is make sure we disable this for now by default and then we can ask as soon as possible

**Comment by codygarver** [comment]
`fwupd` wasn't used by anything and it looked like messing with remotes will break it so I removed it from the iso until how it works can be sorted out when it eventually does get implemented in AppCenter in elementary/appcenter#498

**Comment by AlonsoEnrique** [comment]
@codygarver is possible install and use fwupd for update my laptop firmware on Juno? any problem?

**Comment by codygarver** [comment]
@AlonsoEnrique it should work fine, it's unmodified, but I haven't tested it myself.
