### ISSUE TITLE
Package Godot

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#92]
Not super urgent, but a number of games require Godot to be built. It might make sense to package Godot and carry it in the PPA so devs can more easily ship their games, plus we can more easily build their games on Houston.

**Comment by danrabbit** [comment]
Do we still want to do this or are we going to rely on Flatpak for games?

**Comment by cassidyjames** [comment]
Yeah it's probably sane to lean on Flatpak unless it's stupidly easy to package this.

**Comment by danrabbit** [comment]
Closing then :+1:
