### ISSUE TITLE
Generate `appstream-data-pantheon` generation for Stable PPA

### ISSUE THREAD

**Issue by codygarver** [elementary/os#96]
Do we still need this?

**Comment by btkostner** [comment]
As far as I know, launchpad still does not have appstream support, so we will need it until we move away from launchpad, or they add support for appstream in ppas.

**Comment by tintou** [comment]
From Colin Watson, Launchpad engineer:
> hmm, I think not as it stands at the moment - the dep11 support for the primary archive is done by an external scanner maintained by the Ubuntu team whose output we sync automatically from Launchpad, which would be a pretty heavyweight thing to spin up for PPAs.  I'm not sure how that would/could work

**Comment by codygarver** [comment]
Part of my intended scope for this bug was also figure out a way to improve the process for generating and keeping this package up-to-date. So since it's been determined this package is staying, I will re-purpose this issue.

**Comment by danrabbit** [comment]
We could just publish apps through Houston ;)

**Comment by codygarver** [comment]
Done.
