### ISSUE TITLE
[juno beta1] Issues with default window sizes and location for application

### ISSUE THREAD

**Issue by arshubham** [elementary/os#97]
This seems to affect most of the applications. On first run and every subsequent run (if window size not changed) the app window opens and are larger in height than width making the experience less than optimal. They also cover the plank, making it auto-hide. Ideally windows should open in the center and  shouldn't cover the plank as in loki.
![screenshot from 2018-07-03 14-58-02](https://user-images.githubusercontent.com/14235191/42240688-160d47ba-7ed6-11e8-9883-e4a79a691a04.png)
![screenshot from 2018-07-03 14-55-54](https://user-images.githubusercontent.com/14235191/42240690-1944c5fc-7ed6-11e8-823f-95768a44f8f4.png)
![screenshot from 2018-07-03 14-58-06](https://user-images.githubusercontent.com/14235191/42240695-1c5fb86e-7ed6-11e8-8076-1f6eb9e6119c.png)
![screenshot from 2018-07-03 15-26-18](https://user-images.githubusercontent.com/14235191/42240698-1f40511a-7ed6-11e8-986a-84bcc50a032c.png)

Again, if the window size and location is modified, it respects it, so it just the matter of initial defaults.

System Resolution 1366x768 (16:9)

**Comment by blureshadow** [comment]
I posted a bounty on this issue: https://www.bountysource.com/issues/60442566-juno-beta1-issues-with-default-window-sizes-and-location-for-application

**Comment by danrabbit** [comment]
This can't be solved os-wide, we'll need to adjust each app individually since they request their own default sizes. 

Closing for OS since there's no cure-all.

Please open individual issues for affected apps
