### ISSUE TITLE
[juno beta1] Middle click to paste is not working between different applications

### ISSUE THREAD

**Issue by arshubham** [elementary/os#98]
Middle click to paste is not working between different applications. For example I can select and paste from Firefox to terminal or vice versa. I first thought this may be a Firefox issue but this also doesn't seem to work with the combination of code - Firefox and code - terminal. Although I am able to use the middle click within an application. Therefore if I select something in terminal I can middle click paste it in terminal but not in code.

**Comment by wout** [comment]
My issue is probably related. I don't use middle click paste and I want it to be disabled. But the toggle in the System Settings doesn't work. I can still middle click paste even if the toggle is off.

![image](https://user-images.githubusercontent.com/107324/47260009-81fee400-d4b3-11e8-862a-be80a3d14a1c.png)

**Comment by micahilbery** [comment]
I haven't been able to middle click paste at all regardless of switch status since the toggle was added.

**Comment by arshubham** [comment]
> I haven't been able to middle click paste at all regardless of switch status since the toggle was added.

In the juno stable I don't see the toggle at all. Was present in beta and only disabled/enabled middle click within an application.

**Comment by DanyGee** [comment]
In Juno Stable the toggle is present:
![screenshot from 2018-10-23 13 57 13 2x](https://user-images.githubusercontent.com/26818551/47358949-961d2e00-d6cb-11e8-8987-2b613e06c3b0.png)
