### ISSUE TITLE
Automatically install libreoffice-gtk when installing a LibreOffice app

### ISSUE THREAD

**Issue by jlnr** [elementary/os#99]
I've recently needed to work with an Excel file, so I went to AppCenter and installed LibreOffice Calc. It looks terrible out of the box:

<img width="997" alt="before" src="https://user-images.githubusercontent.com/70772/42276362-dfad2e06-7f93-11e8-811b-df76c1bff24d.png">

After some googling I've installed the `libreoffice-gtk` package, which is what makes LibreOffice reasonably pretty on Ubuntu, and it also helps a lot on elementaryOS:

<img width="1362" alt="after" src="https://user-images.githubusercontent.com/70772/42276403-f6eb5e08-7f93-11e8-846c-79aac30ae89b.png">

I suggest making this package (`libreoffice-gtk`) a dependency of all LibreOffice apps on elementaryOS, so that the version from AppCenter looks as good as possible.

Screenshots from Juno beta 1.

**Comment by jlnr** [comment]
Ah, thanks for pointing out that there is a GTK 3 version as well. This is what LibreOffice from flathub looks like, which is the same as LibreOffice from AppCenter when I install the `libreoffice-gtk3` package:

<img width="870" alt="flatpak" src="https://user-images.githubusercontent.com/70772/42277416-99ad6b10-7f97-11e8-92e3-5cddadd8c79f.png">

I don't think it looks as polished as the GTK 2 version: There are no blue highlights for the selected row/column, the font picker seems too flat for elementaryOS, and the "close document" button has the wrong background (not shown in the screenshot). But I have no strong feeling either way, I just think that one of the `libreoffice-gtk*` packages should be installed along with LibreOffice by default.

**Comment by arshubham** [comment]
@jlnr This may be due to the fact that elementary theme in flatpak may be old. Atleast it is better than the gtk2 version out there. Try using smaller icons, it will look better.

**Comment by danrabbit** [comment]
AFAIK, it's not possible to make libreoffice pull in this package unless elementary were to carry patches for LibreOffice. This should be reported upstream to Ubuntu where these packages come from.

Closing as "Out of scope" since elementary doesn't maintain packages for LibreOffice

**Comment by jlnr** [comment]
Fair enough. I'm not sure how Ubuntu handles this in its new "minimal" installation, which is similar to the situation in elementaryOS (no LibreOffice by default); I'll take a look.
